/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JTextField;
import jonxujin.Main;
import Excepciones.Error;
import javax.swing.JOptionPane;

/**
 *
 * @author 1gprogexa15
 */
public class Alta extends javax.swing.JFrame {

    /**
     * Creates new form Alta
     */
    public Alta() {
        initComponents();
        datos();
    }

    private void datos(){
        this.setLocationRelativeTo(null);
        Main.datos(cGenero);
        cGenero.setSelectedIndex(-1);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gTipo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        tTitulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cGenero = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        rActor = new javax.swing.JRadioButton();
        rDirector = new javax.swing.JRadioButton();
        rGuinista = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        tNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tFecha = new javax.swing.JTextField();
        bAñadir = new javax.swing.JButton();
        bAceptar = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Título:");

        tTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTituloActionPerformed(evt);
            }
        });

        jLabel2.setText("Género:");

        cGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cGeneroActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Personas que intervienen"));

        gTipo.add(rActor);
        rActor.setText("Actor");
        rActor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rActorActionPerformed(evt);
            }
        });

        gTipo.add(rDirector);
        rDirector.setText("Director");

        gTipo.add(rGuinista);
        rGuinista.setText("Guinista");

        jLabel3.setText("Nombre:");

        tNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNombreActionPerformed(evt);
            }
        });

        jLabel4.setText("Fecha de Nacimiento:");

        bAñadir.setText("Añadir");
        bAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAñadirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rActor)
                        .addGap(18, 18, 18)
                        .addComponent(rDirector)
                        .addGap(18, 18, 18)
                        .addComponent(rGuinista))
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bAñadir)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rActor)
                    .addComponent(rDirector)
                    .addComponent(rGuinista))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(bAñadir))
        );

        bAceptar.setText("Aceptar");
        bAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAceptarActionPerformed(evt);
            }
        });

        bCancelar.setText("Salir");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tTitulo)
                                    .addComponent(cGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bCancelar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAceptar)
                    .addComponent(bCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tTituloActionPerformed

    private void rActorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rActorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rActorActionPerformed

    private void cGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cGeneroActionPerformed

    private void tNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNombreActionPerformed

    private void bAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAñadirActionPerformed
        // TODO add your handling code here:
        try{
            validar(4, tNombre.getText(), "^[A-Z][a-z]{1,}([ ][A-Z][a-z]{1,})*$", tNombre);
            validar(5, tFecha.getText(), "^[0-9]{1,2}[-][0-9]{1,2}[-][0-9]{4}$", tFecha);
            if(gTipo.getSelection() == null){
                throw new Error(3);
            }
            else{
                if(rActor.isSelected()){
                    Main.agregarPersona(1, tNombre.getText(), tFecha.getText());
                }
                else if(rDirector.isSelected()){
                    Main.agregarPersona(2, tNombre.getText(), tFecha.getText());
                }
                else{
                    Main.agregarPersona(3, tNombre.getText(), tFecha.getText());
                }
                JOptionPane.showMessageDialog(this, "Agregado Correctamente.");
                borrar();
            }
        }
        catch(Error e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getClass());
        }
    }//GEN-LAST:event_bAñadirActionPerformed

    private void bAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAceptarActionPerformed
        // TODO add your handling code here:
        try{
            validar(1, tTitulo.getText(), "^[A-Z][a-z]{1,}([ ][A-Z][a-z]{1,})*$", tTitulo);
            if(cGenero.getSelectedIndex()<0){
                cGenero.setBackground(Color.red);
                cGenero.grabFocus();
                throw new Error(2);
            }
            else{
                cGenero.setBackground(Color.white);
            }
            estadoAlta(Main.agregarTitulo(tTitulo.getText(), cGenero.getSelectedItem().toString()));
            
            borrarTodo();
        }
        catch(Error e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getClass());
        }
    }//GEN-LAST:event_bAceptarActionPerformed

    private void estadoAlta(boolean estado) throws Exception{
        if(estado){
            JOptionPane.showMessageDialog(this, "Alta realizada correctamente.");
        }
        else{
            throw new Error(6);
        }
    }
    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        // TODO add your handling code here:
        
        JOptionPane.showMessageDialog(this, Main.mostrar());
        Main.cerrar(this);
    }//GEN-LAST:event_bCancelarActionPerformed

    private void borrar(){
        rActor.setSelected(false);
        rDirector.setSelected(false);
        rGuinista.setSelected(false);
        tNombre.setText("");
        tFecha.setText("");
    }
    private void borrarTodo(){
        tTitulo.setText("");
        cGenero.setSelectedIndex(-1);
        rActor.setSelected(false);
        rDirector.setSelected(false);
        rGuinista.setSelected(false);
        tNombre.setText("");
        tFecha.setText("");
    }
    private void validar(int cod, String dato, String patron, JTextField campo) throws Exception{
        Pattern p = Pattern.compile(patron);
        Matcher m = p.matcher(dato);
        if(m.matches()){
            campo.setBackground(Color.white);
        }
        else{
            campo.setBackground(Color.red);
            campo.grabFocus();
            throw new Error(cod);
        }
    }
 
    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAceptar;
    private javax.swing.JButton bAñadir;
    private javax.swing.JButton bCancelar;
    private javax.swing.JComboBox<String> cGenero;
    private javax.swing.ButtonGroup gTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rActor;
    private javax.swing.JRadioButton rDirector;
    private javax.swing.JRadioButton rGuinista;
    private javax.swing.JTextField tFecha;
    private javax.swing.JTextField tNombre;
    private javax.swing.JTextField tTitulo;
    // End of variables declaration//GEN-END:variables
}
