/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Persona;
import alta_persona.AltaPersona;
import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
/**
 *
 * @author v6222
 */
public class VPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VPrincipal
     */
    public VPrincipal() {
        initComponents();
        bEliminar.hide();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bAceptar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        tfNombre = new javax.swing.JTextField();
        tfApellidos = new javax.swing.JTextField();
        tfDni = new javax.swing.JTextField();
        lAyuda = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfCurso = new javax.swing.JTextField();
        bEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Alta Personas");
        setLocation(new java.awt.Point(300, 300));

        jLabel1.setText("Nombre");

        jLabel2.setText("Apellidos");

        jLabel3.setText("DNI");

        bAceptar.setText("Aceptar");
        bAceptar.setEnabled(false);
        bAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAceptarActionPerformed(evt);
            }
        });
        bAceptar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bAceptarKeyPressed(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tfNombre.setEditable(false);
        tfNombre.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tfNombreCaretUpdate(evt);
            }
        });
        tfNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfNombreFocusGained(evt);
            }
        });

        tfApellidos.setEditable(false);
        tfApellidos.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tfApellidosCaretUpdate(evt);
            }
        });
        tfApellidos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfApellidosFocusGained(evt);
            }
        });

        tfDni.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tfDniCaretUpdate(evt);
            }
        });
        tfDni.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfDniFocusGained(evt);
            }
        });

        lAyuda.setForeground(new java.awt.Color(255, 51, 51));
        lAyuda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lAyuda.setText("Alta de Personas");
        lAyuda.setToolTipText("");

        jLabel5.setText("Curso");

        tfCurso.setEditable(false);
        tfCurso.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tfCursoCaretUpdate(evt);
            }
        });
        tfCurso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfCursoFocusGained(evt);
            }
        });

        bEliminar.setText("Eliminar");
        bEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lAyuda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bAceptar)
                                .addGap(108, 108, 108)
                                .addComponent(bEliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 258, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tfApellidos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                    .addComponent(tfNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                    .addComponent(tfDni, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                    .addComponent(tfCurso, javax.swing.GroupLayout.Alignment.LEADING))))
                        .addGap(35, 35, 35))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(tfDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(97, 97, 97)
                .addComponent(lAyuda)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAceptar)
                    .addComponent(jButton2)
                    .addComponent(bEliminar))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAceptarActionPerformed
        // TODO add your handling code here:
            tfCurso.setText(tfCurso.getText().toUpperCase());
            Persona p;
            if(v == null){
                p = new Persona();
                p.setNombre(tfNombre.getText());
                p.setApellidos(tfApellidos.getText());
                p.setDni(tfDni.getText());
            }
            else{
                p = v;
            }
            
            p.setCurso(tfCurso.getText());
            AltaPersona.crear(p);
            tfNombre.setText("");
            tfApellidos.setText("");
            tfDni.setText("");
            tfCurso.setText("");
            tfApellidos.setEditable(false);
            tfNombre.setEditable(false);
            tfCurso.setEditable(false);
            bAceptar.setEnabled(false);
            tfDni.grabFocus();
            bEliminar.hide();
            v = null;
    }//GEN-LAST:event_bAceptarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        VDiseñoPrevio vd = new VDiseñoPrevio();
        vd.setVisible(true);
        vd.recibir();
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tfNombreCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tfNombreCaretUpdate
        // TODO add your handling code here:
        if(validar(tfNombre.getText(),"^[A-Z][a-z]{2,}([ ][A-Z][a-z]{1,})*$")){
            tfApellidos.setEditable(true);
            tfNombre.setForeground(Color.blue);
        }
        else{
            tfNombre.setForeground(Color.red);
        }
        
    }//GEN-LAST:event_tfNombreCaretUpdate

    private void tfApellidosCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tfApellidosCaretUpdate
        // TODO add your handling code here:
        if(validar(tfApellidos.getText(),"^[A-Z][a-z]{1,}([ ][A-Z][a-z]{1,})*$")){
            tfCurso.setEditable(true);
            tfApellidos.setForeground(Color.blue);
        }
        else{
            tfApellidos.setForeground(Color.red);
        }
    }//GEN-LAST:event_tfApellidosCaretUpdate

    private void tfDniCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tfDniCaretUpdate
        // TODO add your handling code here:
        if(validar(tfDni.getText(),"^[0-9]{8}[A-Z]$")){
            tfDni.setForeground(Color.blue);
            for(Persona e : AltaPersona.listaPersona){
                if(e.getDni().equals(tfDni.getText())){
                    tfNombre.setEditable(true);
                    tfApellidos.setEditable(true);
                    tfCurso.setEditable(true);
                    tfCurso.grabFocus();
                    tfNombre.setText(e.getNombre());
                    tfApellidos.setText(e.getApellidos());
                    tfCurso.setText(e.getCurso());
                    bEliminar.show();
                    v = e;
                }
            }
            tfNombre.setEditable(true);
            tfDni.setForeground(Color.blue);
            if(!tfNombre.getText().isEmpty()){
                tfCurso.grabFocus();
                lAyuda.setText("Si desea cambiar el curso, modifique el campo curso. Para eliminar la persona, pulse eliminar.");
            }
            else{
                tfNombre.grabFocus();
                v = null;
            }
        }
            else{
            tfDni.setForeground(Color.red);
        }
                
    }//GEN-LAST:event_tfDniCaretUpdate

    private void tfApellidosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfApellidosFocusGained
        // TODO add your handling code here:
        lAyuda.setText("Apellidos: Primero mayúscula, seguidos en minúsculas, mínimo 2 caracteres.");
    }//GEN-LAST:event_tfApellidosFocusGained

    private void tfDniFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDniFocusGained
        // TODO add your handling code here:
        lAyuda.setText("DNI: 8 números y una letra en mayúscula.");
    }//GEN-LAST:event_tfDniFocusGained

    private void tfNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNombreFocusGained
        // TODO add your handling code here:
        lAyuda.setText("Nombre simple o compuesto: Primero mayúscula, seguido minúsculas, mínimo 3 caracteres.");
    }//GEN-LAST:event_tfNombreFocusGained

    private void bAceptarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bAceptarKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar()== KeyEvent.VK_ENTER){
            tfCurso.setText(tfCurso.getText().toUpperCase());
            Persona p;
            if(v == null){
                p = new Persona();
                p.setNombre(tfNombre.getText());
                p.setApellidos(tfApellidos.getText());
                p.setDni(tfDni.getText());
            }
            else{
                p = v;
            }
            
            p.setCurso(tfCurso.getText());
            AltaPersona.crear(p);
            tfNombre.setText("");
            tfApellidos.setText("");
            tfDni.setText("");
            tfCurso.setText("");
            tfApellidos.setEditable(false);
            tfNombre.setEditable(false);
            tfCurso.setEditable(false);
            bAceptar.setEnabled(false);
            tfDni.grabFocus();
            bEliminar.hide();
            v = null;
        }
    }//GEN-LAST:event_bAceptarKeyPressed

    private void tfCursoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tfCursoCaretUpdate
        // TODO add your handling code here:
        if(validar(tfCurso.getText(),"^[A-Da-d][1-4]$")){
            bAceptar.setEnabled(true);
            tfCurso.setForeground(Color.blue);
            bAceptar.grabFocus();
        }
        else{
            tfCurso.setForeground(Color.red);
        }
    }//GEN-LAST:event_tfCursoCaretUpdate

    private void tfCursoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCursoFocusGained
        // TODO add your handling code here:
        lAyuda.setText("Curso: Letra (A,B,C o D) más nº de curso (1,2,3 o 4), 2 caracteres (A1, D2,...).");
    }//GEN-LAST:event_tfCursoFocusGained

    private void bEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarActionPerformed
        // TODO add your handling code here:
        AltaPersona.borrar(v);
        tfNombre.setText("");
        tfApellidos.setText("");
        tfDni.setText("");
        tfCurso.setText("");
        tfApellidos.setEditable(false);
        tfNombre.setEditable(false);
        tfCurso.setEditable(false);
        bAceptar.setEnabled(false);
        tfDni.grabFocus();
        v = null;
        bEliminar.hide();
    }//GEN-LAST:event_bEliminarActionPerformed

    public static boolean validar(String valor, String condicion){
        boolean visible = false;
        Pattern patron = Pattern.compile(condicion);
        Matcher mat = patron.matcher(valor);
        if(mat.matches()){
            visible = true;
        }
        else{
            visible = false;
        }
        return visible;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VPrincipal().setVisible(true);
                
            }
        });
    }
    private Persona v;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAceptar;
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lAyuda;
    private javax.swing.JTextField tfApellidos;
    private javax.swing.JTextField tfCurso;
    private javax.swing.JTextField tfDni;
    private javax.swing.JTextField tfNombre;
    // End of variables declaration//GEN-END:variables
}
