/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controladora.Main;
import UML.Empleado;
import Errores.Error;
import UML.Contrato;
import UML.Nomina;
import java.awt.Image;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.util.Calendar;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author v6222
 */
public class dNomina extends javax.swing.JDialog {

    /**
     * Creates new form dNomina
     */
    Empleado empleado;
    Nomina nomina;
    Calendar fecha = Calendar.getInstance();
    MaskFormatter formatearTexto, formatearImporte;
    double cuotaExtra, cuotaForzosa;
    
    public dNomina(String titulo) {
        super();
        initComponents();
        adaptaciones(titulo);
    }

    private void adaptaciones(String titulo){
        setTitle(titulo);
        setModal(true);
        setLocationRelativeTo(null);
        try{
            formatearTexto = new MaskFormatter("########-#");
            formatearTexto.setPlaceholderCharacter('_');
        }
        catch (ParseException e){
            JOptionPane.showMessageDialog(this, e.getClass());
        }
        cuotaExtra = 10.00;
        cuotaForzosa = 15.00;
        jLabel9.setText("Extra " + cuotaExtra + " €:");
        jLabel10.setText("Hora Forzosa " + cuotaForzosa + " €:");
        if(!this.getTitle().equals("Confeccionar Nómina")){
            lDato.setText("Nº Nómina:");
        }
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lDato = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lFoto = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tCargo = new javax.swing.JTextField();
        tContrato = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tNSS = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cMes = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tDia = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tBase = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tP1 = new javax.swing.JTextField();
        tP2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tP33 = new javax.swing.JTextField();
        tP111 = new javax.swing.JTextField();
        tP11 = new javax.swing.JTextField();
        tP3 = new javax.swing.JTextField();
        tP55 = new javax.swing.JTextField();
        tP5 = new javax.swing.JTextField();
        tP44 = new javax.swing.JTextField();
        tP4 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tPTotal = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        tO2 = new javax.swing.JTextField();
        tO1 = new javax.swing.JTextField();
        tO11 = new javax.swing.JTextField();
        tO22 = new javax.swing.JTextField();
        tO222 = new javax.swing.JTextField();
        tO111 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        tO4 = new javax.swing.JTextField();
        tO3 = new javax.swing.JTextField();
        tO33 = new javax.swing.JTextField();
        tO44 = new javax.swing.JTextField();
        tO444 = new javax.swing.JTextField();
        tO333 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        tOTotal = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        tNeto = new javax.swing.JTextField();
        bConfeccionar = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();
        tExtra = new javax.swing.JFormattedTextField(new DecimalFormat("#,###.00"));
        tIncentivo = new javax.swing.JFormattedTextField(new DecimalFormat("#,###.00"));
        tForzosa = new javax.swing.JFormattedTextField(new DecimalFormat("#,###.00"));
        tEmpleado = new javax.swing.JFormattedTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        tP6 = new javax.swing.JTextField();
        tP66 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        tP7 = new javax.swing.JTextField();
        tP77 = new javax.swing.JTextField();
        tP88 = new javax.swing.JTextField();
        tP8 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        tO55 = new javax.swing.JTextField();
        tO555 = new javax.swing.JTextField();
        tO5 = new javax.swing.JTextField();
        tO6 = new javax.swing.JTextField();
        tO66 = new javax.swing.JTextField();
        tO666 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lDato.setText("Cod. Empleado/DNI:");

        jButton1.setText("Localizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 153)));

        jLabel2.setText("Nombre y Apellidos:");

        tNombre.setEditable(false);

        jLabel3.setText("Cargo:");

        tCargo.setEditable(false);

        tContrato.setEditable(false);

        jLabel4.setText("Tipo de Contrato:");

        tNSS.setEditable(false);

        jLabel5.setText("Número S.S.:");

        cMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cMes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cMesItemStateChanged(evt);
            }
        });

        jLabel6.setText("Mes a Confeccionar:");

        jLabel7.setText("Nº de Días:");

        tDia.setEditable(false);
        tDia.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel8.setText("Incentivos Euros:");

        jLabel9.setText("Extra 10 €:");

        jLabel10.setText("Hora Forzosa 15 €:");

        jLabel13.setText("Base + Contrato:");

        tBase.setEditable(false);
        tBase.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Cuota Patronal:");

        jLabel12.setText("C. Comun:");

        tP1.setEditable(false);
        tP1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tP2.setEditable(false);
        tP2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("-->   Desempleo:");

        jLabel15.setText("C. Profesionales:");

        jLabel16.setText("-->");

        tP33.setEditable(false);
        tP33.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tP111.setEditable(false);
        tP111.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tP11.setEditable(false);
        tP11.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tP3.setEditable(false);
        tP3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tP55.setEditable(false);
        tP55.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tP5.setEditable(false);
        tP5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tP44.setEditable(false);
        tP44.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tP4.setEditable(false);
        tP4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Total Cuota:");

        tPTotal.setEditable(false);
        tPTotal.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        tPTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tPTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPTotalActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("Cuota Obrera + IRPF:");

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("Ct. común:");

        jLabel20.setText("Desempleo:");

        tO2.setEditable(false);
        tO2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tO1.setEditable(false);
        tO1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tO11.setEditable(false);
        tO11.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tO22.setEditable(false);
        tO22.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tO222.setEditable(false);
        tO222.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tO111.setEditable(false);
        tO111.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel21.setText("FP:");

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel22.setText("H. Extra:");

        tO4.setEditable(false);
        tO4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tO3.setEditable(false);
        tO3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tO33.setEditable(false);
        tO33.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tO44.setEditable(false);
        tO44.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tO444.setEditable(false);
        tO444.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tO333.setEditable(false);
        tO333.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Total Cuota:");

        tOTotal.setEditable(false);
        tOTotal.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        tOTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setText("Total Neto:");

        tNeto.setEditable(false);
        tNeto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tNeto.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        bConfeccionar.setText("Calcular");
        bConfeccionar.setEnabled(false);
        bConfeccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConfeccionarActionPerformed(evt);
            }
        });

        bSalir.setText("Salir");
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });

        tExtra.setEditable(false);
        tExtra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tExtra.setText("0,00");

        tIncentivo.setEditable(false);
        tIncentivo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tIncentivo.setText("0,00");

        tForzosa.setEditable(false);
        tForzosa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tForzosa.setText("0,00");

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel25.setText("-->   AT + EP:");

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel26.setText("-->   FP:");

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel27.setText("-->   FOGASA:");

        tP6.setEditable(false);
        tP6.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tP66.setEditable(false);
        tP66.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel28.setText("Horas Extras:");

        jLabel29.setText("Fuerza Mayor:");

        tP7.setEditable(false);
        tP7.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tP77.setEditable(false);
        tP77.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tP88.setEditable(false);
        tP88.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tP8.setEditable(false);
        tP8.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel30.setText("Forzosa:");

        tO55.setEditable(false);
        tO55.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tO555.setEditable(false);
        tO555.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tO5.setEditable(false);
        tO5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tO6.setEditable(false);
        tO6.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tO66.setEditable(false);
        tO66.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tO666.setEditable(false);
        tO666.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel32.setText("IRPF:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(tO3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tO2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tO6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tP1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                                            .addComponent(tO1, javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addGap(6, 6, 6)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tO33, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                                    .addComponent(tO66))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tO666, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tO333, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(tO5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tO4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tO44, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                                            .addComponent(tO55))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tO444, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tO555, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(tO22, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                                            .addComponent(tO11))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(tP6, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                                            .addComponent(tP4)
                                            .addComponent(tP3)
                                            .addComponent(tP5)
                                            .addComponent(tP11))
                                        .addGap(6, 6, 6)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tP111, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                                    .addComponent(tP33, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tP44, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tO111, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tO222, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tP66)
                                    .addComponent(tP55, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tPTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                            .addComponent(tOTotal)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(tP8, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tP88, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(tP7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tP77, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lDato)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tNSS)
                            .addComponent(tContrato)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(tEmpleado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addComponent(tNombre)
                            .addComponent(tCargo)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cMes, 0, 79, Short.MAX_VALUE)
                                    .addComponent(tForzosa))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tDia, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(tExtra, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tIncentivo)
                                    .addComponent(tBase)))
                            .addComponent(lFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bConfeccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addGap(15, 15, 15)
                                .addComponent(tNeto, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel18))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel15))
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tP2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(220, 220, 220)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lFoto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lDato)
                            .addComponent(jButton1)
                            .addComponent(tEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tNSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(tDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(tBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(tExtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tIncentivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(tForzosa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(tP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tP33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(tP7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tP77, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tP4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tP44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(tP8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tP88, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(tP5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tP55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(tP6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tP66, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tP111, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tP11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(0, 2, Short.MAX_VALUE))
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tPTotal, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tO1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tO111, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tO11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(tO44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tO444, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tO5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tO2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(tO222, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tO22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(tO55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tO555, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tO4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tO3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tO33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tO333, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tO6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32)
                            .addComponent(tO66, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tO666, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tNeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bSalir)
                            .addComponent(bConfeccionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tOTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(this.getTitle().equals("Confeccionar Nómina")){
            confeccionar();
        }
        else if(this.getTitle().equals("Modificar Nómina")){
            tExtra.setEditable(true);
            tForzosa.setEditable(true);
            tIncentivo.setEditable(true);
            bConfeccionar.setEnabled(true);
            modificar();
        }
        else{
            modificar();
            bConfeccionar.setText("Eliminar");
            bConfeccionar.setEnabled(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void confeccionar(){
        try{
            empleado = Main.localizar(tEmpleado.getText());
            if(empleado != null){
                tEmpleado.setText(String.valueOf(empleado.getCod()));
                tNombre.setText(empleado.getNombre());
                tCargo.setText(empleado.getCargo().getNombre() + "-" + empleado.getCargo().getCargo());
                tContrato.setText(empleado.getContrato().getContrato());
                tNSS.setText(empleado.getNss());
                double base = empleado.getCargo().getSalarioBase() + empleado.getContrato().getSalarioBase();
                DecimalFormat forma = new DecimalFormat("0.##");
                tBase.setText(String.valueOf(forma.format(base)));
                tExtra.setEditable(true);
                tForzosa.setEditable(true);
                tIncentivo.setEditable(true);
                bConfeccionar.setEnabled(true);
                foto();
            }
            else{
                throw new Error(11);
            }
        }
        catch(Error e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    private void foto(){
        ImageIcon imagen = new ImageIcon("src/FotosEmpleados/" + tEmpleado.getText() + ".jpg");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(lFoto.getWidth(), lFoto.getHeight(), Image.SCALE_DEFAULT));
        lFoto.setIcon(icono);
        lFoto.repaint();
    }
    private void modificar(){
        try{
            nomina = Main.localizarNomina(Integer.parseInt(tEmpleado.getText()));
            if(nomina != null){
                empleado = Main.empleado;
                tEmpleado.setText(String.valueOf(nomina.getCod()));
                tNombre.setText(empleado.getNombre());
                tCargo.setText(empleado.getCargo().getNombre() + "-" + empleado.getCargo().getCargo());
                tContrato.setText(empleado.getContrato().getContrato());
                tNSS.setText(empleado.getNss());
                double base = empleado.getCargo().getSalarioBase() + empleado.getContrato().getSalarioBase();
                DecimalFormat forma = new DecimalFormat("0.##");
                tBase.setText(String.valueOf(forma.format(base)));
                foto();
                
                Contrato c = nomina.getC();

                tP1.setText(String.valueOf(forma.format(nomina.getSalarioBase())));
                tP11.setText(String.valueOf(forma.format(c.geteContingenciasComunes())));
                tP111.setText(String.valueOf(forma.format(nomina.geteContingenciasComunes())));
                tP2.setText(String.valueOf(forma.format(nomina.getSalarioBaseC())));
                tP3.setText(String.valueOf(forma.format(c.getAtep())));
                tP33.setText(String.valueOf(forma.format(nomina.getAtep())));
                tP4.setText(String.valueOf(forma.format(c.geteDesempleo())));
                tP44.setText(String.valueOf(forma.format(nomina.geteDesempleo())));
                tP5.setText(String.valueOf(forma.format(c.geteFP())));
                tP55.setText(String.valueOf(forma.format(nomina.geteFP())));
                tP6.setText(String.valueOf(forma.format(c.getFogasa())));
                tP66.setText(String.valueOf(forma.format(nomina.getFogasa())));
                tP7.setText(String.valueOf(forma.format(c.geteHorasExtras())));
                tP77.setText(String.valueOf(forma.format(nomina.geteHorasExtras())));
                tP8.setText(String.valueOf(forma.format(c.geteExtraFuerza())));
                tP88.setText(String.valueOf(forma.format(nomina.geteExtraFuerza())));
                tPTotal.setText(String.valueOf(forma.format(nomina.getCoutaPatronal()))+"€");

                tO1.setText(String.valueOf(forma.format(nomina.getSalarioBase())));
                tO11.setText(String.valueOf(forma.format(c.getContingenciasComunes())));
                tO111.setText(String.valueOf(forma.format(nomina.getContingenciasComunes())));
                tO2.setText(String.valueOf(forma.format(nomina.getSalarioBaseC())));
                tO22.setText(String.valueOf(forma.format(c.getDesempleao())));
                tO222.setText(String.valueOf(forma.format(nomina.getDesempleao())));
                tO3.setText(String.valueOf(forma.format(nomina.getSalarioBaseC())));
                tO33.setText(String.valueOf(forma.format(c.getFp())));
                tO333.setText(String.valueOf(forma.format(nomina.getFp())));
                tO4.setText(String.valueOf(forma.format(nomina.getExtra()*nomina.getCuotaExtra())));
                tO44.setText(String.valueOf(forma.format(c.getHorasExtras())));
                tO444.setText(String.valueOf(forma.format(nomina.getHorasExtras())));
                tO5.setText(String.valueOf(forma.format(nomina.getForzosa()*nomina.getCuotaForzosa())));
                tO55.setText(String.valueOf(forma.format(c.getExtraFuerza())));
                tO555.setText(String.valueOf(forma.format(nomina.getExtraFuerza())));
                tO6.setText(String.valueOf(forma.format(nomina.getIrpf()/(c.getIrpf()/100))));
                tO66.setText(String.valueOf(forma.format(c.getIrpf())));
                tO666.setText(String.valueOf(forma.format(nomina.getIrpf())));
                tOTotal.setText(String.valueOf(forma.format(nomina.getCuotaObrera()))+"€");
                tNeto.setText(String.valueOf(forma.format(nomina.getNeto()))+"€");
                bConfeccionar.setText("Calcular");
                
                tExtra.setText(String.valueOf(forma.format(nomina.getExtra())));
                tForzosa.setText(String.valueOf(forma.format(nomina.getForzosa())));
                tIncentivo.setText(String.valueOf(forma.format(nomina.getIncentivo())));
                
                jButton1.setEnabled(false);
                tEmpleado.setEnabled(false);
            }
            else{
                throw new Error(12);
            }
        }
        catch(Error e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        catch (Exception ee){
            JOptionPane.showMessageDialog(this, ee.getClass());
        }
    }
    
    private void eliminar(){
        try{
            Main.eliminarNomina(nomina);
            Main.reabrir(2,this.getTitle(), this);
        }
        catch (Exception ee){
            JOptionPane.showMessageDialog(this, ee.getClass());
        }
    }
 
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:        
        cMes.setSelectedIndex(fecha.get(Calendar.MONTH));
    }//GEN-LAST:event_formWindowOpened

    private void cMesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cMesItemStateChanged
        // TODO add your handling code here:
        fecha.set(Calendar.YEAR, cMes.getSelectedIndex(), 1);
        tDia.setText(String.valueOf(fecha.getActualMaximum(fecha.DAY_OF_MONTH)));
        
    }//GEN-LAST:event_cMesItemStateChanged

    private void calcular(){
        
        DecimalFormat forma = new DecimalFormat("#0.00");
        jButton1.setEnabled(false);
        tEmpleado.setEnabled(false);
        tForzosa.setEnabled(false);
        tExtra.setEnabled(false);
        tIncentivo.setEnabled(false);
        Nomina nomina = Main.calcNomina(this.getTitle(),Integer.parseInt(tEmpleado.getText()), Double.parseDouble(tBase.getText().replace(",", ".")),
                Double.parseDouble(tExtra.getText().replace(",", ".")),Double.parseDouble(tForzosa.getText().replace(",", ".")),
                Double.parseDouble(tIncentivo.getText().replace(",", ".")), cuotaExtra, cuotaForzosa, 
                Integer.parseInt(cMes.getSelectedItem().toString()), Integer.parseInt(tDia.getText()));
        Contrato c = nomina.getC();
        tP1.setText(String.valueOf(forma.format(nomina.getSalarioBase())));
        tP11.setText(String.valueOf(forma.format(c.geteContingenciasComunes())));
        tP111.setText(String.valueOf(forma.format(nomina.geteContingenciasComunes())));
        tP2.setText(String.valueOf(forma.format(nomina.getSalarioBaseC())));
        tP3.setText(String.valueOf(forma.format(c.getAtep())));
        tP33.setText(String.valueOf(forma.format(nomina.getAtep())));
        tP4.setText(String.valueOf(forma.format(c.geteDesempleo())));
        tP44.setText(String.valueOf(forma.format(nomina.geteDesempleo())));
        tP5.setText(String.valueOf(forma.format(c.geteFP())));
        tP55.setText(String.valueOf(forma.format(nomina.geteFP())));
        tP6.setText(String.valueOf(forma.format(c.getFogasa())));
        tP66.setText(String.valueOf(forma.format(nomina.getFogasa())));
        tP7.setText(String.valueOf(forma.format(c.geteHorasExtras())));
        tP77.setText(String.valueOf(forma.format(nomina.geteHorasExtras())));
        tP8.setText(String.valueOf(forma.format(c.geteExtraFuerza())));
        tP88.setText(String.valueOf(forma.format(nomina.geteExtraFuerza())));
        tPTotal.setText(String.valueOf(forma.format(nomina.getCoutaPatronal()))+"€");
        tO1.setText(String.valueOf(forma.format(nomina.getSalarioBase())));
        tO11.setText(String.valueOf(forma.format(c.getContingenciasComunes())));
        tO111.setText(String.valueOf(forma.format(nomina.getContingenciasComunes())));
        tO2.setText(String.valueOf(forma.format(nomina.getSalarioBaseC())));
        tO22.setText(String.valueOf(forma.format(c.getDesempleao())));
        tO222.setText(String.valueOf(forma.format(nomina.getDesempleao())));
        tO3.setText(String.valueOf(forma.format(nomina.getSalarioBaseC())));
        tO33.setText(String.valueOf(forma.format(c.getFp())));
        tO333.setText(String.valueOf(forma.format(nomina.getFp())));
        tO4.setText(String.valueOf(forma.format(nomina.getExtra()*nomina.getCuotaExtra())));
        tO44.setText(String.valueOf(forma.format(c.getHorasExtras())));
        tO444.setText(String.valueOf(forma.format(nomina.getHorasExtras())));
        tO5.setText(String.valueOf(forma.format(nomina.getForzosa()*nomina.getCuotaForzosa())));
        tO55.setText(String.valueOf(forma.format(c.getExtraFuerza())));
        tO555.setText(String.valueOf(forma.format(nomina.getExtraFuerza())));
        tO6.setText(String.valueOf(forma.format(nomina.getIrpf()/(c.getIrpf()/100))));
        tO66.setText(String.valueOf(forma.format(c.getIrpf())));
        tO666.setText(String.valueOf(forma.format(nomina.getIrpf())));
        tOTotal.setText(String.valueOf(forma.format(nomina.getCuotaObrera()))+"€");
        tNeto.setText(String.valueOf(forma.format(nomina.getNeto()))+"€");
    }
    
    private void bConfeccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConfeccionarActionPerformed
            // TODO add your handling code here:
        try{
            if(bConfeccionar.getText().equals("Calcular")){
                calcular();
                bConfeccionar.setText("Continuar");
            }
            else{
                switch(this.getTitle()){
                    case "Confeccionar Nómina":
                        Main.agregarNomina(0);
                        Main.reabrir(2,this.getTitle(), this);
                        break;
                        
                    case "Modificar Nómina":
                        Main.eliminarNomina(nomina);
                        Main.agregarNomina(1);
                        Main.reabrir(2,this.getTitle(), this);
                        break;
                        
                    case "Eliminar Nómina":
                        eliminar();
                        break;
                        
                }
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getClass());
        }
    }//GEN-LAST:event_bConfeccionarActionPerformed

    private void tPTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tPTotalActionPerformed

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        // TODO add your handling code here:
        Main.cerrar(this);
    }//GEN-LAST:event_bSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bConfeccionar;
    private javax.swing.JButton bSalir;
    private javax.swing.JComboBox<String> cMes;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lDato;
    private javax.swing.JLabel lFoto;
    private javax.swing.JTextField tBase;
    private javax.swing.JTextField tCargo;
    private javax.swing.JTextField tContrato;
    private javax.swing.JTextField tDia;
    private javax.swing.JFormattedTextField tEmpleado;
    private javax.swing.JFormattedTextField tExtra;
    private javax.swing.JFormattedTextField tForzosa;
    private javax.swing.JFormattedTextField tIncentivo;
    private javax.swing.JTextField tNSS;
    private javax.swing.JTextField tNeto;
    private javax.swing.JTextField tNombre;
    private javax.swing.JTextField tO1;
    private javax.swing.JTextField tO11;
    private javax.swing.JTextField tO111;
    private javax.swing.JTextField tO2;
    private javax.swing.JTextField tO22;
    private javax.swing.JTextField tO222;
    private javax.swing.JTextField tO3;
    private javax.swing.JTextField tO33;
    private javax.swing.JTextField tO333;
    private javax.swing.JTextField tO4;
    private javax.swing.JTextField tO44;
    private javax.swing.JTextField tO444;
    private javax.swing.JTextField tO5;
    private javax.swing.JTextField tO55;
    private javax.swing.JTextField tO555;
    private javax.swing.JTextField tO6;
    private javax.swing.JTextField tO66;
    private javax.swing.JTextField tO666;
    private javax.swing.JTextField tOTotal;
    private javax.swing.JTextField tP1;
    private javax.swing.JTextField tP11;
    private javax.swing.JTextField tP111;
    private javax.swing.JTextField tP2;
    private javax.swing.JTextField tP3;
    private javax.swing.JTextField tP33;
    private javax.swing.JTextField tP4;
    private javax.swing.JTextField tP44;
    private javax.swing.JTextField tP5;
    private javax.swing.JTextField tP55;
    private javax.swing.JTextField tP6;
    private javax.swing.JTextField tP66;
    private javax.swing.JTextField tP7;
    private javax.swing.JTextField tP77;
    private javax.swing.JTextField tP8;
    private javax.swing.JTextField tP88;
    private javax.swing.JTextField tPTotal;
    // End of variables declaration//GEN-END:variables
}
