/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controladora.Main;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Jon
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     * @param usuario
     */
    
      
    public Principal(String usuario) {
        initComponents();
        setSize(1088, 732+jToolBar1.size().height);
        setLocationRelativeTo(null);
        adaptaciones();
        lBienvenido.setText("Bienvenid@ " + usuario);
    }

    private void adaptaciones(){
        ImageIcon imagen=new ImageIcon("src/img/pantalla.jpg");
	Icon icono= new ImageIcon(imagen.getImage().getScaledInstance(lFondo.getWidth(), lFondo.getHeight(),Image.SCALE_DEFAULT));
	lFondo.setIcon(icono);
	lFondo.repaint();
        imagenBoton("src/img/alta.jpg",bAlta);
        imagenBoton("src/img/modificar.jpg",bModificar);
        imagenBoton("src/img/baja.jpg",bBaja);
        imagenBoton("src/img/empleado.jpg",bNomina);
        imagenBoton("src/img/contrato.jpg",bNominaMod);
        imagenBoton("src/img/departamento.png",bListadoNomina);
    }
    
    private void imagenBoton(String ruta, javax.swing.JButton boton){
        ImageIcon imagen=new ImageIcon(ruta);
	Icon icono= new ImageIcon(imagen.getImage().getScaledInstance(boton.getWidth(), boton.getHeight(),Image.SCALE_DEFAULT));
	boton.setIcon(icono);
	boton.repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSexo = new javax.swing.ButtonGroup();
        bgCivil = new javax.swing.ButtonGroup();
        jMenuItem7 = new javax.swing.JMenuItem();
        jToolBar1 = new javax.swing.JToolBar();
        bAlta = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        bModificar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        bBaja = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        bNomina = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        bNominaMod = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        bListadoNomina = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lBienvenido = new javax.swing.JLabel();
        lFondo = new javax.swing.JLabel();
        mMenu = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        iAlta = new javax.swing.JMenuItem();
        iModificación = new javax.swing.JMenuItem();
        iBaja = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mListado = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        jMenuItem7.setText("jMenuItem7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Empresa X");
        setSize(new java.awt.Dimension(841, 544));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jToolBar1.setRollover(true);
        jToolBar1.setPreferredSize(new java.awt.Dimension(90, 9));

        bAlta.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        bAlta.setToolTipText("ALTA");
        bAlta.setFocusable(false);
        bAlta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bAlta.setMaximumSize(new java.awt.Dimension(40, 40));
        bAlta.setVerifyInputWhenFocusTarget(false);
        bAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAltaActionPerformed(evt);
            }
        });
        jToolBar1.add(bAlta);
        jToolBar1.add(jSeparator2);

        bModificar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        bModificar.setToolTipText("MODIFICACIÓN");
        bModificar.setFocusable(false);
        bModificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bModificar.setMaximumSize(new java.awt.Dimension(40, 40));
        bModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificarActionPerformed(evt);
            }
        });
        jToolBar1.add(bModificar);
        jToolBar1.add(jSeparator3);

        bBaja.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        bBaja.setToolTipText("BAJA");
        bBaja.setFocusable(false);
        bBaja.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bBaja.setMaximumSize(new java.awt.Dimension(40, 40));
        bBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBajaActionPerformed(evt);
            }
        });
        jToolBar1.add(bBaja);
        jToolBar1.add(jSeparator4);

        bNomina.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        bNomina.setToolTipText("CREAR NÓMINA");
        bNomina.setFocusable(false);
        bNomina.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bNomina.setMaximumSize(new java.awt.Dimension(40, 40));
        bNomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNominaActionPerformed(evt);
            }
        });
        jToolBar1.add(bNomina);
        jToolBar1.add(jSeparator5);

        bNominaMod.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        bNominaMod.setToolTipText("MODIFICAR NÓMINA");
        bNominaMod.setFocusable(false);
        bNominaMod.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bNominaMod.setMaximumSize(new java.awt.Dimension(40, 40));
        bNominaMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNominaModActionPerformed(evt);
            }
        });
        jToolBar1.add(bNominaMod);
        jToolBar1.add(jSeparator6);

        bListadoNomina.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        bListadoNomina.setToolTipText("LISTADO NÓMINA");
        bListadoNomina.setFocusable(false);
        bListadoNomina.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bListadoNomina.setMaximumSize(new java.awt.Dimension(40, 40));
        bListadoNomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bListadoNominaActionPerformed(evt);
            }
        });
        jToolBar1.add(bListadoNomina);

        getContentPane().add(jToolBar1);
        jToolBar1.setBounds(0, 0, 1090, 43);

        jLabel1.setText("Indica qué operación desea realizar.");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 160, 260, 14);

        lBienvenido.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lBienvenido.setText("jLabel1");
        getContentPane().add(lBienvenido);
        lBienvenido.setBounds(60, 90, 430, 29);
        getContentPane().add(lFondo);
        lFondo.setBounds(0, 40, 1090, 660);

        jMenu3.setText("Personas");

        iAlta.setText("Alta");
        iAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iAltaActionPerformed(evt);
            }
        });
        jMenu3.add(iAlta);

        iModificación.setText("Modificación");
        iModificación.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iModificaciónActionPerformed(evt);
            }
        });
        jMenu3.add(iModificación);

        iBaja.setText("Baja");
        iBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iBajaActionPerformed(evt);
            }
        });
        jMenu3.add(iBaja);
        jMenu3.add(jSeparator1);

        mListado.setText("Listado");

        jMenuItem1.setText("Por Número de Empleado");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mListado.add(jMenuItem1);

        jMenuItem2.setText("Por Contrato");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        mListado.add(jMenuItem2);

        jMenuItem3.setText("Por Departamento");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        mListado.add(jMenuItem3);

        jMenu3.add(mListado);

        mMenu.add(jMenu3);

        jMenu1.setText("Nominas");

        jMenuItem4.setText("Confeccionar");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("Modificar");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem6.setText("Eliminar");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);
        jMenu1.add(jSeparator7);

        jMenuItem8.setText("Listado de Nóminas");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        mMenu.add(jMenu1);

        jMenu4.setText("Salir");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        mMenu.add(jMenu4);

        setJMenuBar(mMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
        Main.salir(this);
    }//GEN-LAST:event_jMenu4MouseClicked

    private void bAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAltaActionPerformed
        // TODO add your handling code here:
        Main.ventana(1,"Alta del Empleado");
    }//GEN-LAST:event_bAltaActionPerformed

    private void iAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iAltaActionPerformed
        // TODO add your handling code here:
        Main.ventana(1,"Alta del Empleado");
    }//GEN-LAST:event_iAltaActionPerformed

    private void iModificaciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iModificaciónActionPerformed
        // TODO add your handling code here:
        Main.ventana(1,"Modificación del Empleado");
    }//GEN-LAST:event_iModificaciónActionPerformed

    private void iBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iBajaActionPerformed
        // TODO add your handling code here:
        Main.ventana(1,"Baja del Empleado");
    }//GEN-LAST:event_iBajaActionPerformed

    private void bModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificarActionPerformed
        // TODO add your handling code here:
        Main.ventana(1,"Modificación del Empleado");
    }//GEN-LAST:event_bModificarActionPerformed

    private void bBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBajaActionPerformed
        // TODO add your handling code here:
        Main.ventana(1,"Baja del Empleado");
    }//GEN-LAST:event_bBajaActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        Main.ventana(2,"Confeccionar Nómina");
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void bNominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNominaActionPerformed
        // TODO add your handling code here:
        Main.ventana(2,"Confeccionar Nómina");
    }//GEN-LAST:event_bNominaActionPerformed

    private void bNominaModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNominaModActionPerformed
        // TODO add your handling code here:
        Main.ventana(2,"Modificar Nómina");
    }//GEN-LAST:event_bNominaModActionPerformed

    private void bListadoNominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bListadoNominaActionPerformed
        // TODO add your handling code here:
        Main.ventana(3,"Listado Nominas");
    }//GEN-LAST:event_bListadoNominaActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        Main.ventana(2,"Modificar Nómina");
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        Main.ventana(2,"Eliminar Nómina");
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        Main.ventana(3,"Listado Nominas");
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Main.ventana(3,"Listado por Número de Empleado");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        Main.ventana(3,"Listado por Contrato");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        Main.ventana(3,"Listado por Departamento");
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        Main.salir(this);
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAlta;
    private javax.swing.JButton bBaja;
    private javax.swing.JButton bListadoNomina;
    private javax.swing.JButton bModificar;
    private javax.swing.JButton bNomina;
    private javax.swing.JButton bNominaMod;
    private javax.swing.ButtonGroup bgCivil;
    private javax.swing.ButtonGroup bgSexo;
    private javax.swing.JMenuItem iAlta;
    private javax.swing.JMenuItem iBaja;
    private javax.swing.JMenuItem iModificación;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lBienvenido;
    private javax.swing.JLabel lFondo;
    private javax.swing.JMenu mListado;
    private javax.swing.JMenuBar mMenu;
    // End of variables declaration//GEN-END:variables
}
