/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controladora.Main;
import Excepcion.Error;
import UML.*;
import java.awt.Color;
import java.time.LocalTime;
import java.text.*;
import java.util.*;
import java.util.regex.*;
import javax.swing.*;
import org.freixas.jcalendar.JCalendarCombo;

/**
 *
 * @author Jon
 */
public class vEvento extends javax.swing.JDialog {

    int n;
    /**
     * Creates new form vEventos
     * @param n
     */
    public vEvento(int n) {
        super();
        initComponents();
        this.n = n;
        adaptaciones(n);
    }

    private void adaptaciones(int n){
        setModal(true);
        setLocationRelativeTo(null);
        pEmpresa.setVisible(false);
        pPersona.setVisible(false);
        this.setSize(555, 225);
        
        for(int x = 0; x<25; x++){
            String y = String.valueOf(x);
            if(x<10){
                y = "0" + x;
            }
            cIHora.addItem(String.valueOf(y));
            cFHora.addItem(String.valueOf(y));
        }
        
        for(int x = 0; x<60; x++){
            String y = String.valueOf(x);
            if(x<10){
                y = "0" + x;
            }
            cIMinuto.addItem(String.valueOf(y));
            cFMinuto.addItem(String.valueOf(y));
        }
                
        switch(n){
            case 1:
                this.setTitle("Alta Evento");
                bBuscar.setEnabled(false);
                jListar.setEnabled(false);
                mostrarBAlta();
                bAceptar.setEnabled(true);
                break;
                
            case 2:
                this.setTitle("Modificar Evento");
                bAceptar.setText("Modificar");
                break;
                
            case 3:
                this.setTitle("Eliminar Evento");
                bAceptar.setText("Eliminar");
                break;
                
            case 4:
                this.setTitle("Confirmar Asistencia");
                bAceptar.setText("Confirmar");
                break;
        }
        
        setVisible(true);
    }

    private void mostrarBAlta(){
        cFecha.setEnabled(true);
        tLugar.setEnabled(true);
        cIHora.setEnabled(true);
        cIMinuto.setEnabled(true);
        cFHora.setEnabled(true);
        cFMinuto.setEnabled(true);
        tPlaza.setEnabled(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tEvento = new javax.swing.JTextField();
        bBuscar = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();
        tPlaza = new javax.swing.JTextField();
        tLugar = new javax.swing.JTextField();
        bAtras = new javax.swing.JButton();
        bInicio = new javax.swing.JButton();
        bAdelante = new javax.swing.JButton();
        bFin = new javax.swing.JButton();
        bAceptar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cIHora = new javax.swing.JComboBox<>();
        cIMinuto = new javax.swing.JComboBox<>();
        cFHora = new javax.swing.JComboBox<>();
        cFMinuto = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cFecha = new org.freixas.jcalendar.JCalendarCombo();
        jListar = new javax.swing.JButton();
        pEmpresa = new javax.swing.JPanel();
        tNombreE = new javax.swing.JTextField();
        lDireccion1 = new javax.swing.JLabel();
        lDNI1 = new javax.swing.JLabel();
        tCIF = new javax.swing.JTextField();
        tTelefonoE = new javax.swing.JTextField();
        tDireccionE = new javax.swing.JTextField();
        lDNI2 = new javax.swing.JLabel();
        lDireccion2 = new javax.swing.JLabel();
        bEmpresa = new javax.swing.JButton();
        pPersona = new javax.swing.JPanel();
        tTelefono = new javax.swing.JTextField();
        tEdad = new javax.swing.JTextField();
        lTelefono = new javax.swing.JLabel();
        lDireccion = new javax.swing.JLabel();
        tDNI = new javax.swing.JTextField();
        tDireccion = new javax.swing.JTextField();
        tApellidos = new javax.swing.JTextField();
        lApellidos = new javax.swing.JLabel();
        tNombre = new javax.swing.JTextField();
        lNombre = new javax.swing.JLabel();
        lDNI = new javax.swing.JLabel();
        lEdad = new javax.swing.JLabel();
        bPersona = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Eventos");

        bBuscar.setText("Buscar Por Nombre");
        bBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarActionPerformed(evt);
            }
        });

        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        tPlaza.setEnabled(false);

        tLugar.setEnabled(false);

        bAtras.setText("<");
        bAtras.setEnabled(false);
        bAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAtrasActionPerformed(evt);
            }
        });

        bInicio.setText("|<");
        bInicio.setEnabled(false);
        bInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInicioActionPerformed(evt);
            }
        });

        bAdelante.setText(">");
        bAdelante.setEnabled(false);
        bAdelante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAdelanteActionPerformed(evt);
            }
        });

        bFin.setText(">|");
        bFin.setEnabled(false);
        bFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFinActionPerformed(evt);
            }
        });

        bAceptar.setText("Añadir");
        bAceptar.setEnabled(false);
        bAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAceptarActionPerformed(evt);
            }
        });

        jLabel9.setText("Fecha:");

        jLabel10.setText("Hora Inicio:");

        jLabel12.setText("Hora Fin:");

        jLabel11.setText("Plazas:");

        jLabel8.setText("Lugar:");

        jLabel7.setText("Evento:");

        cIHora.setEnabled(false);

        cIMinuto.setEnabled(false);

        cFHora.setEnabled(false);

        cFMinuto.setEnabled(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(":");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(":");

        cFecha.setEnabled(false);

        jListar.setText("Listar EV");
        jListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jListarActionPerformed(evt);
            }
        });

        pEmpresa.setBorder(javax.swing.BorderFactory.createTitledBorder("Empresa de la persona Asistente"));

        tNombreE.setEnabled(false);

        lDireccion1.setText("Empresa:");

        lDNI1.setText("CIF:");

        tTelefonoE.setEnabled(false);

        tDireccionE.setEnabled(false);

        lDNI2.setText("Telf:");

        lDireccion2.setText("Dirección:");

        bEmpresa.setText("Comprobar Empresa");
        bEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEmpresaActionPerformed(evt);
            }
        });

        pPersona.setBorder(javax.swing.BorderFactory.createTitledBorder("Persona que asiste al Evento"));

        tTelefono.setEnabled(false);

        tEdad.setEnabled(false);

        lTelefono.setText("Teléfono:");

        lDireccion.setText("Dirección:");

        tDireccion.setEnabled(false);

        tApellidos.setEnabled(false);

        lApellidos.setText("Apellidos:");

        tNombre.setEnabled(false);

        lNombre.setText("Nombre:");

        lDNI.setText("DNI:");

        lEdad.setText("Edad:");

        bPersona.setText("Comprobar Persona");
        bPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPersonaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pPersonaLayout = new javax.swing.GroupLayout(pPersona);
        pPersona.setLayout(pPersonaLayout);
        pPersonaLayout.setHorizontalGroup(
            pPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPersonaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pPersonaLayout.createSequentialGroup()
                        .addGroup(pPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lEdad)
                            .addComponent(lDNI)
                            .addComponent(lDireccion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tDireccion)
                            .addGroup(pPersonaLayout.createSequentialGroup()
                                .addComponent(tEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lTelefono)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tTelefono))))
                    .addGroup(pPersonaLayout.createSequentialGroup()
                        .addComponent(lNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pPersonaLayout.createSequentialGroup()
                                .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lApellidos))
                            .addComponent(tDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bPersona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tApellidos))))
                .addContainerGap())
        );
        pPersonaLayout.setVerticalGroup(
            pPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPersonaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lDNI)
                    .addComponent(bPersona))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lApellidos)
                    .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lEdad)
                    .addComponent(lTelefono)
                    .addComponent(tTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lDireccion))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pEmpresaLayout = new javax.swing.GroupLayout(pEmpresa);
        pEmpresa.setLayout(pEmpresaLayout);
        pEmpresaLayout.setHorizontalGroup(
            pEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEmpresaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pEmpresaLayout.createSequentialGroup()
                        .addGroup(pEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lDireccion1)
                            .addComponent(lDNI1)
                            .addComponent(lDNI2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pEmpresaLayout.createSequentialGroup()
                                .addComponent(tTelefonoE, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lDireccion2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tDireccionE))
                            .addComponent(tNombreE)
                            .addGroup(pEmpresaLayout.createSequentialGroup()
                                .addComponent(tCIF)
                                .addGap(18, 18, 18)
                                .addComponent(bEmpresa))))
                    .addComponent(pPersona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pEmpresaLayout.setVerticalGroup(
            pEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEmpresaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tCIF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lDNI1)
                    .addComponent(bEmpresa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tNombreE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lDireccion1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tTelefonoE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lDNI2)
                    .addComponent(lDireccion2)
                    .addComponent(tDireccionE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bInicio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bAtras)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bAdelante)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bFin))
                            .addComponent(tEvento)
                            .addComponent(tPlaza, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tLugar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jListar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cIHora, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cFHora, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cIMinuto, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cFMinuto, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bCancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bBuscar)
                    .addComponent(jListar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bInicio)
                    .addComponent(bAtras)
                    .addComponent(bFin)
                    .addComponent(bAdelante)
                    .addComponent(jLabel9)
                    .addComponent(cFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(cIHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(cIMinuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tPlaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(cFHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(cFMinuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAceptar)
                    .addComponent(bCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        // TODO add your handling code here:
        Main.cerrar(this);
    }//GEN-LAST:event_bCancelarActionPerformed

    private LocalTime oHora(String hora, String minuto){
        return LocalTime.of(Integer.parseInt(hora), Integer.parseInt(minuto));
    }
    
    private java.sql.Date oFecha(Date fecha){
        SimpleDateFormat formar = new SimpleDateFormat("yyyy-MM-dd");
        String fFecha = formar.format(fecha);
        return java.sql.Date.valueOf(fFecha);
    }
    
    private void aceptarOP1() throws Exception{
        LocalTime horaI, horaF;
        validar(1, tEvento,"^[A-Z][a-z0-9 ]+$");
        validar(2, tLugar,"^[A-Z][a-z0-9 ]+$");
        validar(3, tPlaza,"^[0-9]+$");
        validarFecha(4, cFecha);
        if(Main.consultar(tEvento.getText()) == null){
            horaI = oHora(cIHora.getSelectedItem().toString(), cIMinuto.getSelectedItem().toString());
            horaF = oHora(cFHora.getSelectedItem().toString(), cFMinuto.getSelectedItem().toString());
            Main.añadir(tEvento.getText(), tLugar.getText(), horaI, horaF, oFecha(cFecha.getDate()), Integer.parseInt(tPlaza.getText()));
            JOptionPane.showMessageDialog(this, "Añadido Correctamente.");
            Main.reabrir(this,1);
        }
        else{
            throw new Error(11);
        }
    }
    
    private void aceptarOP2() throws Exception{
        LocalTime horaI, horaF;
        validar(1, tEvento,"^[A-Z][a-z0-9 ]+$");
        validar(2, tLugar,"^[A-Z][a-z0-9 ]+$");
        validar(3, tPlaza,"^[0-9]+$");
        validarFecha(4, cFecha);
        horaI = oHora(cIHora.getSelectedItem().toString(), cIMinuto.getSelectedItem().toString());
        horaF = oHora(cFHora.getSelectedItem().toString(), cFMinuto.getSelectedItem().toString());
        Main.modificar(tEvento.getText(), tLugar.getText(), horaI, horaF, oFecha(cFecha.getDate()), Integer.parseInt(tPlaza.getText()));
        JOptionPane.showMessageDialog(this, "Modificado Correctamente.");
        Main.reabrir(this,2);
    }
    
    private void bAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAceptarActionPerformed
        try {
            // TODO add your handling code here:
            switch(n){
                case 1:
                    aceptarOP1();
                    break;
                    
                case 2:
                    aceptarOP2();
                    break;
                    
                case 3:
                    Main.eliminar(tEvento.getText());
                    JOptionPane.showMessageDialog(this, "Eliminado Correctamente.");
                    Main.reabrir(this,3);
                    break;
                    
                case 4:
                    JOptionPane.showMessageDialog(this, Main.asistir(tEvento.getText()));
                    Main.reabrir(this,4);
                    break;
                    
            }
        }
        catch(Error e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        catch (Exception ee) {
            JOptionPane.showMessageDialog(this, ee.getClass());
        }
    }//GEN-LAST:event_bAceptarActionPerformed

    private void validar(int error, JTextField dato, String patron) throws Exception{
        Pattern p = Pattern.compile(patron);
        Matcher m = p.matcher(dato.getText());
        if(m.matches()){
            dato.setBackground(Color.white);
        }
        else{
            dato.setBackground(Color.red);
            dato.grabFocus();
            throw new Error(error);
        }
    }
    
    private void validarFecha(int error, JCalendarCombo dato) throws Exception{
        java.util.Date fecha = new java.util.Date();
        if(dato.getDate().after(fecha)){
            dato.setBackground(Color.white);
        }
        else{
            dato.setBackground(Color.red);
            dato.grabFocus();
            throw new Error(error);
        }
    }
    
    private void bBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarActionPerformed
        // TODO add your handling code here:
        try{
            Evento ev = Main.consultar(tEvento.getText());
            if(ev == null){
                throw new Error(15);
            }
            else
            {
                switch (n) {
                    case 1:
                        bAceptar.setEnabled(true);
                        break;
                        
                    case 2:
                        mostrarBAlta();
                        cFecha.setVisible(true);
                        cargarDatos(ev);
                        bAceptar.setEnabled(true);
                        break;
                        
                    case 3:
                        cargarDatos(ev);
                        bAceptar.setEnabled(true);
                        break;
                        
                    case 4:
                        cargarDatos(ev);
                        pEmpresa.setVisible(true);
                        pPersona.setVisible(false);
                        this.setSize(555, 340);
                        break;
                }
            }
        }
        catch(Error e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        catch(Exception ee){
            JOptionPane.showMessageDialog(this, ee.getMessage());
        }
            
    }//GEN-LAST:event_bBuscarActionPerformed

    private void jListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jListarActionPerformed
        // TODO add your handling code here:
        try{
            bAceptar.setEnabled(true);
            cargarDatos(Main.recibirEvento());
                if(n==2){
                    mostrarBAlta();
                    cFecha.setVisible(true);
                    bAceptar.setEnabled(true);
                }
                else if (n == 4){
                    this.setSize(555, 340);
                    pEmpresa.setVisible(true);
                    pPersona.setVisible(false);
                    bAceptar.setEnabled(false);
                }
                bAdelante.setEnabled(true);
                bInicio.setEnabled(true);
                bAtras.setEnabled(true);
                bFin.setEnabled(true);
        }
        catch(Error e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        catch(Exception ee){
            JOptionPane.showMessageDialog(this, ee.getMessage());
        }
    }//GEN-LAST:event_jListarActionPerformed

    private void bInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInicioActionPerformed
        // TODO add your handling code here:
        moverRegistro(0);
        JOptionPane.showMessageDialog(this, "El actual es el Primer registro.");
        
    }//GEN-LAST:event_bInicioActionPerformed

    private void bAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAtrasActionPerformed
        // TODO add your handling code here:
        moverRegistro(-1);
    }//GEN-LAST:event_bAtrasActionPerformed

    private void bAdelanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAdelanteActionPerformed
        // TODO add your handling code here:
        moverRegistro(1);
    }//GEN-LAST:event_bAdelanteActionPerformed

    private void bFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFinActionPerformed
        // TODO add your handling code here:
        moverRegistro(-10);
        JOptionPane.showMessageDialog(this, "El actual es el Último registro.");
    }//GEN-LAST:event_bFinActionPerformed

    private void moverRegistro(int n){
        try{
            cargarDatos(Main.moverEvento(n));
        }
        catch(Error e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        catch(Exception ee){
            JOptionPane.showMessageDialog(this, ee.getClass());
        }
    }
    private void bEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEmpresaActionPerformed
        try{ 
        validar(12, tCIF,"^[A-Z][0-9]{8}$");
        tCIF.setEnabled(false);
        if(bEmpresa.getText().equals("Comprobar Empresa")){
            Empresa em;
            em = Main.consultarEmpresa(tCIF.getText());
            if(em == null){
                bEmpresa.setText("Añadir Empresa");
                tNombreE.setEnabled(true);
                tTelefonoE.setEnabled(true);
                tDireccionE.setEnabled(true);
            }
            else{
                tNombreE.setText(em.getNombre());
                tDireccionE.setText(em.getDireccion());
                tTelefonoE.setText(em.getTelefono());
                pPersona.setVisible(true);
                this.setSize(555, 525);
            }
        }
        else{
            validar(13, tNombreE,"^[A-Z][a-z. ]+$");
            validar(10, tTelefonoE,"^[6-9][0-9]{8}$");
            validar(8, tDireccionE,"^[A-Z][a-z0-9 ]+$");
            tNombreE.setEnabled(false);
            tTelefonoE.setEnabled(false);
            tDireccionE.setEnabled(false);
            Main.añadirEmpresa(tCIF.getText(), tNombreE.getText(), tTelefonoE.getText(), tDireccionE.getText());
            bEmpresa.setEnabled(false);
            pPersona.setVisible(true);
            this.setSize(555, 520);
        }
        } catch (Error e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        } catch (Exception ee) {
            JOptionPane.showMessageDialog(this, ee.getClass());
        }
    }//GEN-LAST:event_bEmpresaActionPerformed

    private void enComun(boolean estado){
        tNombre.setEnabled(estado);
        tApellidos.setEnabled(estado);
        tDireccion.setEnabled(estado);
        tEdad.setEnabled(estado);
        tTelefono.setEnabled(estado);
    }
    
    private void bPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPersonaActionPerformed
        // TODO add your handling code here:
        try{
            validar(7, tDNI, "^[0-9]{8}[A-Z]$");
            tDNI.setEnabled(false);
            
        if(bPersona.getText().equals("Comprobar Persona")){
            if(!Main.consultarPersona(tDNI.getText())){
                bPersona.setText("Añadir Persona");
                enComun(true);
            }
            else{
                Persona p = Main.getP();
                if(tCIF.getText().equals(Main.getEm().getCif())){
                    tNombre.setText(p.getNombre());
                    tApellidos.setText(p.getApellidos());
                    tDireccion.setText(p.getDireccion());
                    tEdad.setText(String.valueOf(p.getEdad()));
                    tTelefono.setText(p.getTelefono());
                    enComun(false);
                    bAceptar.setEnabled(true);
                }
                else{
                    tDNI.setEnabled(true);
                    tDNI.grabFocus();
                    tNombre.setText("");
                    tApellidos.setText("");
                    tDireccion.setText("");
                    tEdad.setText("");
                    tTelefono.setText("");
                    throw new Error(14);
                }
            }
        }
        else{
            validar(5, tNombre, "^[A-Z][a-z ]+$");
            validar(6, tApellidos, "^[A-Z][a-z ]+$");
            validar(8, tDireccion, "^[A-Z][a-z0-9 ]+$");
            validar(9, tEdad, "^[0-9]{1,3}$");
            validar(10, tTelefono, "^[6-9][0-9]{8}$");
            enComun(false);
            Main.añadirPersona( tNombre.getText(), tApellidos.getText(), tDNI.getText(), tDireccion.getText(), 
                    tTelefono.getText(), Integer.parseInt(tEdad.getText()), tCIF.getText());
            bPersona.setEnabled(false);
            bAceptar.setEnabled(true);
        }
        } catch (Error e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        } catch (Exception ee) {
            JOptionPane.showMessageDialog(this, ee.getClass());
        }
        
    }//GEN-LAST:event_bPersonaActionPerformed

    private void cargarDatos(Evento ev){
        tEvento.setEnabled(false);
        tEvento.setText(ev.getNombre());
        tLugar.setText(ev.getLugar());
        tPlaza.setText(String.valueOf(ev.getAforo()));
        cFecha.setDate(ev.getFecha());
        cIHora.setSelectedItem(hora(ev.gethEntrada()));
        cIMinuto.setSelectedItem(minuto(ev.gethEntrada()));
        cFHora.setSelectedItem(hora(ev.gethSalida()));
        cFMinuto.setSelectedItem(minuto(ev.gethSalida()));
    }
    
    private String hora(LocalTime h){
        return h.toString().substring(0, 2);
    }
    
    private String minuto(LocalTime h){
        return h.toString().substring(3, 5);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAceptar;
    private javax.swing.JButton bAdelante;
    private javax.swing.JButton bAtras;
    private javax.swing.JButton bBuscar;
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bEmpresa;
    private javax.swing.JButton bFin;
    private javax.swing.JButton bInicio;
    private javax.swing.JButton bPersona;
    private javax.swing.JComboBox<String> cFHora;
    private javax.swing.JComboBox<String> cFMinuto;
    private org.freixas.jcalendar.JCalendarCombo cFecha;
    private javax.swing.JComboBox<String> cIHora;
    private javax.swing.JComboBox<String> cIMinuto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jListar;
    private javax.swing.JLabel lApellidos;
    private javax.swing.JLabel lDNI;
    private javax.swing.JLabel lDNI1;
    private javax.swing.JLabel lDNI2;
    private javax.swing.JLabel lDireccion;
    private javax.swing.JLabel lDireccion1;
    private javax.swing.JLabel lDireccion2;
    private javax.swing.JLabel lEdad;
    private javax.swing.JLabel lNombre;
    private javax.swing.JLabel lTelefono;
    private javax.swing.JPanel pEmpresa;
    private javax.swing.JPanel pPersona;
    private javax.swing.JTextField tApellidos;
    private javax.swing.JTextField tCIF;
    private javax.swing.JTextField tDNI;
    private javax.swing.JTextField tDireccion;
    private javax.swing.JTextField tDireccionE;
    private javax.swing.JTextField tEdad;
    private javax.swing.JTextField tEvento;
    private javax.swing.JTextField tLugar;
    private javax.swing.JTextField tNombre;
    private javax.swing.JTextField tNombreE;
    private javax.swing.JTextField tPlaza;
    private javax.swing.JTextField tTelefono;
    private javax.swing.JTextField tTelefonoE;
    // End of variables declaration//GEN-END:variables
}
