/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controladora.Main;
import UML.*;
import Errores.Error;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author v6222
 */
public class Buscar extends javax.swing.JDialog {

    int n;
    DefaultTableModel model;
    /**
     * Creates new form Buscar
     */
    public Buscar(int n) {
        initComponents();
        this.n = n;
        
        adaptaciones();
    }
 
    public void adaptaciones(){
        setModal(true);
        tDNI.setVisible(false);
        tNombre.setVisible(false);
        tApellido1.setVisible(false);
        tApellido2.setVisible(false);
        tTelefono.setVisible(false);
        tExpediente.setVisible(false);
        tEstado.setVisible(false);
        lDNI.setVisible(false);
        lNombre.setVisible(false);
        lApellido1.setVisible(false);
        lApellido2.setVisible(false);
        lTelefono.setVisible(false);
        lExpediente.setVisible(false);
        lEstado.setVisible(false);
        
	model = new DefaultTableModel();
	
        
        switch(n){
            case 1:
                setTitle(this.getTitle() + " Abogados");
                visible1();
                Object[] abogados = {"DNI", "Nombre", "Apellido 1", "Apellido 2", "Direccion"};
                model.setColumnIdentifiers(abogados);
                tTabla.setModel(model);
                break;
                
            case 2:
                setTitle(this.getTitle() + " Clientes");
                visible1();
                tTelefono.setVisible(true);
                lTelefono.setVisible(true);
                Object[] clientes = {"DNI", "Nombre", "Apellido 1", "Apellido 2", "Direccion", "Telefono"};
                model.setColumnIdentifiers(clientes);
                tTabla.setModel(model);
                break;
                
            case 3:
                setTitle(this.getTitle() + " Casos");
                visible2();
                Object[] casos = {"Expediente", "Inicio", "Fin", "Estado", "Cliente"};
                model.setColumnIdentifiers(casos);
                tTabla.setModel(model);
                break;
        }
        this.setLocationRelativeTo(null);
        
        setVisible(true);
    }

    
    private void visible1(){
        tDNI.setVisible(true);
        tNombre.setVisible(true);
        tApellido1.setVisible(true);
        tApellido2.setVisible(true);
        lDNI.setVisible(true);
        lNombre.setVisible(true);
        lApellido1.setVisible(true);
        lApellido2.setVisible(true);

    }
    
    private void visible2(){
        
        tExpediente.setVisible(true);
        tEstado.setVisible(true);
        
        lExpediente.setVisible(true);
        lEstado.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lDNI = new javax.swing.JLabel();
        tDNI = new javax.swing.JTextField();
        tNombre = new javax.swing.JTextField();
        lNombre = new javax.swing.JLabel();
        tApellido1 = new javax.swing.JTextField();
        lApellido1 = new javax.swing.JLabel();
        tApellido2 = new javax.swing.JTextField();
        lApellido2 = new javax.swing.JLabel();
        tTelefono = new javax.swing.JTextField();
        lTelefono = new javax.swing.JLabel();
        tExpediente = new javax.swing.JTextField();
        tEstado = new javax.swing.JTextField();
        lExpediente = new javax.swing.JLabel();
        lEstado = new javax.swing.JLabel();
        bBuscar = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tTabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buscar ");

        lDNI.setText("DNI:");

        lNombre.setText("Nombre:");

        lApellido1.setText("Apellido 1:");

        lApellido2.setText("Apellido 2:");

        lTelefono.setText("Teléfono:");

        lExpediente.setText("Expediente:");

        lEstado.setText("Estado:");

        bBuscar.setText("Buscar");
        bBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarActionPerformed(evt);
            }
        });

        bSalir.setText("Salir");
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });

        tTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tTabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(bBuscar)
                            .addGap(346, 346, 346)
                            .addComponent(bSalir))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lTelefono)
                                    .addGap(51, 51, 51)
                                    .addComponent(tTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lDNI)
                                    .addGap(81, 81, 81)
                                    .addComponent(tDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lNombre)
                                    .addGap(56, 56, 56)
                                    .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lApellido1)
                                    .addGap(45, 45, 45)
                                    .addComponent(tApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lApellido2)
                                    .addGap(45, 45, 45)
                                    .addComponent(tApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lExpediente)
                                    .addGap(45, 45, 45)
                                    .addComponent(tExpediente, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lEstado)
                                    .addGap(69, 69, 69)
                                    .addComponent(tEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tExpediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(lExpediente)))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(lEstado))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(lDNI)))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(lNombre)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(lApellido1)))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(lApellido2)))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(lTelefono))
                            .addComponent(tTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSalir)
                    .addComponent(bBuscar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        // TODO add your handling code here:
        Main.cerrar(this);
    }//GEN-LAST:event_bSalirActionPerformed

    private void bBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarActionPerformed
        // TODO add your handling code here:
        try{
            switch(n){
                case 1:
                    cAbogados(Main.listarAbogado(tDNI.getText(), tNombre.getText(), tApellido1.getText(), tApellido2.getText()));
                    break;

                case 2:
                    cClientes(Main.listarClientes(tDNI.getText(), tNombre.getText(), tApellido1.getText(), tApellido2.getText(), tTelefono.getText()));
                    break;

                case 3:
                    cCasos(Main.listarCasos(tExpediente.getText(), tEstado.getText()));
                    break;

            }
        }
        catch (Error e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        } catch (Exception ex) {
            Logger.getLogger(Buscar.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_bBuscarActionPerformed

    private void cAbogados(ArrayList <Abogados> lista) throws Exception{

        if(lista != null){
            model.setRowCount(0);
            for(Abogados abo : lista){
                Object[] fila = {abo.getDni(), abo.getNombre(), abo.getApe1(), abo.getApe2(), abo.getDir()};
                model.addRow(fila);
            }
        }
        else{
            throw new Error(11);
        }
    }
    
    private void cClientes(ArrayList <Clientes> lista) throws Exception{
        if(lista != null){
            model.setRowCount(0);
            for(Clientes clie : lista){
                Object[] fila = {clie.getDni(), clie.getNombre(), clie.getApe1(), clie.getApe2(), clie.getDir(), clie.getTel()};
                model.addRow(fila);
            }
        }
        else{
            throw new Error(11);
        }
    }
    
    private void cCasos(ArrayList <Casos> lista) throws Exception{
        if(lista != null){
            model.setRowCount(0);
            for(Casos caso : lista){
                Object[] fila = {caso.getNumExp(), caso.getFechaI(), caso.getFechaF(), caso.getEstado(), caso.getClientedni()};
                model.addRow(fila);
            }
        }
        else{
            throw new Error(11);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBuscar;
    private javax.swing.JButton bSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lApellido1;
    private javax.swing.JLabel lApellido2;
    private javax.swing.JLabel lDNI;
    private javax.swing.JLabel lEstado;
    private javax.swing.JLabel lExpediente;
    private javax.swing.JLabel lNombre;
    private javax.swing.JLabel lTelefono;
    private javax.swing.JTextField tApellido1;
    private javax.swing.JTextField tApellido2;
    private javax.swing.JTextField tDNI;
    private javax.swing.JTextField tEstado;
    private javax.swing.JTextField tExpediente;
    private javax.swing.JTextField tNombre;
    private javax.swing.JTable tTabla;
    private javax.swing.JTextField tTelefono;
    // End of variables declaration//GEN-END:variables
}
