/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controladora.Main;
import javax.swing.JOptionPane;
import Errores.Error;
import UML.Abogados;
import UML.Casos;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author v6222
 */
public class CasoAbogados extends javax.swing.JDialog {

    int n;
    Casos caso;
    DefaultTableModel model;
    /**
     * Creates new form Estado
     */
    public CasoAbogados(int n, String dato) {
        initComponents();
        this.n = n;
        setTitle(dato + this.getTitle());
        adaptaciones();
    }

    public void adaptaciones(){
        setModal(true);
        caso = null;
        Object[] titulo = {"DNI", "Nombre", "Apellido 1", "Apellido 2", "Direccion"};
	model = new DefaultTableModel();
	model.setColumnIdentifiers(titulo);
        tTablaAbogado.setModel(model);
        this.setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bAceptar = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();
        tEstado = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cFechaI = new org.freixas.jcalendar.JCalendarCombo();
        tNumero = new javax.swing.JTextField();
        cFechaF = new org.freixas.jcalendar.JCalendarCombo();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tAbogado = new javax.swing.JTextField();
        bAnnadir = new javax.swing.JButton();
        bEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tTablaAbogado = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(" Abogado Lleva Caso");
        setName("Estado"); // NOI18N

        jLabel1.setText("Número:");

        bAceptar.setText("Consultar");
        bAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAceptarActionPerformed(evt);
            }
        });

        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        tEstado.setEnabled(false);

        jLabel3.setText("Fecha Fin:");

        tCliente.setEnabled(false);

        jLabel4.setText("Estado:");

        jLabel2.setText("Fecha Inicio:");

        jLabel5.setText("DNI Cliente:");

        cFechaI.setEditable(true);
        cFechaI.setEnabled(false);

        cFechaF.setEditable(true);
        cFechaF.setEnabled(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Abogado"));

        jLabel6.setText("DNI Abogado:");

        tAbogado.setEnabled(false);

        bAnnadir.setText("Añadir Abogado");
        bAnnadir.setEnabled(false);
        bAnnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAnnadirActionPerformed(evt);
            }
        });

        bEliminar.setText("Eliminar Abogado");
        bEliminar.setEnabled(false);
        bEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarActionPerformed(evt);
            }
        });

        tTablaAbogado.setAutoCreateRowSorter(true);
        tTablaAbogado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tTablaAbogado);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tAbogado))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bAnnadir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bEliminar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tAbogado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAnnadir)
                    .addComponent(bEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(47, 47, 47)
                                .addComponent(tNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(24, 24, 24)
                                .addComponent(cFechaI, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(37, 37, 37)
                                .addComponent(cFechaF, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(54, 54, 54)
                                .addComponent(tEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(29, 29, 29)
                                .addComponent(tCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1))
                    .addComponent(tNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addComponent(cFechaI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3))
                    .addComponent(cFechaF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4))
                    .addComponent(tEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel5))
                    .addComponent(tCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAceptar)
                    .addComponent(bCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarDato(){
        cFechaI.setDate(caso.getFechaI());
        cFechaF.setDate(caso.getFechaF());
        tEstado.setText(caso.getEstado());
        tCliente.setText(caso.getClientedni().getDni());
    }
    
    private void cargarLista() throws Exception{
        if(caso.getAbogadosCollection() != null){
            model.setRowCount(0);
            for(Abogados abo : caso.getAbogadosCollection()){
                Object[] fila = {abo.getDni(), abo.getNombre(), abo.getApe1(), abo.getApe2(), abo.getDir()};
                model.addRow(fila);
            }
        }
    }
    
    private void habilitar(){
            cFechaI.setEnabled(true);
            cFechaF.setEnabled(true);
            tEstado.setEnabled(true);
            tAbogado.setEnabled(true);
            bEliminar.setEnabled(true);
            bAnnadir.setEnabled(true);
    }
    
    private void bAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAceptarActionPerformed
        // TODO add your handling code here:
        try{
            if(bAceptar.getText().equals("Consultar")){
                caso = Main.consultarCaso(tNumero.getText());
                if(caso != null){
                    tNumero.setEnabled(false);
                    cargarDato();
                    cargarLista();
                    if(n == 2){
                        bAceptar.setText("Eliminar");
                    }
                    else{
                        habilitar();
                        bAceptar.setText("Aceptar");
                    }
                }
                else{
                    throw new Error(10);
                }
            }
            else{
                siguiente();
            }
        }
        catch(Error e){
            JOptionPane.showMessageDialog(this, e);
        } catch (Exception ex) {
            Logger.getLogger(CasoAbogados.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bAceptarActionPerformed

    public void siguiente() throws Exception{
         if(bAceptar.getText().equals("Aceptar")){
            caso.setEstado(tEstado.getText());
            caso.setFechaI(cFechaI.getDate());
            caso.setFechaF(cFechaF.getDate());
            Main.setCaso(caso);
            Main.modificarCasoSinCambiarClientes();
            JOptionPane.showMessageDialog(this, "Caso Modificado Correctamente.");
            Main.cerrar(this);
        }
        else{
            Main.eliminarCaso(caso.getNumExp());
            JOptionPane.showMessageDialog(this, "Caso Eliminado con sus correspondientes abogados.");
            Main.cerrar(this);
        }
    }
    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        // TODO add your handling code here:
        Main.cerrar(this);
    }//GEN-LAST:event_bCancelarActionPerformed

    private void bAnnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAnnadirActionPerformed
        // TODO add your handling code here:
        try{
            Abogados abo = null;
            abo = Main.consultarAbogado(tAbogado.getText());
            if(abo == null){
                tAbogado.grabFocus();
                throw new Error(7);
            }
            else{
                caso.getAbogadosCollection().add(abo);
                cargarLista();
                tAbogado.setText("");
            }
            
        } catch (Error e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        } catch (Exception ex) {
            Logger.getLogger(CasoAbogados.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_bAnnadirActionPerformed

    private void bEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarActionPerformed
        // TODO add your handling code here:
        try{
            Abogados abo = null;
            abo = Main.consultarAbogado(tAbogado.getText());
            if( abo == null){
                tAbogado.grabFocus();
                throw new Error(7);
            }
            else{
                boolean existe = true;
                for(int x=0; x<tTablaAbogado.getRowCount() && existe; x++){
                    if(tAbogado.getText().equals(tTablaAbogado.getValueAt(x, 0))){
                        caso.getAbogadosCollection().remove(abo);
                        cargarLista();
                        tAbogado.setText("");
                        existe = false;
                    }
                }
                if(existe){
                    throw new Error(8);
                }
            }
            
        } catch (Error e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        } catch (Exception ex) {
            Logger.getLogger(CasoAbogados.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bEliminarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAceptar;
    private javax.swing.JButton bAnnadir;
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bEliminar;
    private org.freixas.jcalendar.JCalendarCombo cFechaF;
    private org.freixas.jcalendar.JCalendarCombo cFechaI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tAbogado;
    private javax.swing.JTextField tCliente;
    private javax.swing.JTextField tEstado;
    private javax.swing.JTextField tNumero;
    private javax.swing.JTable tTablaAbogado;
    // End of variables declaration//GEN-END:variables
}
