/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controladora.Main;
import UML.Clientes;
import Errores.Error;
import UML.Casos;
import java.awt.Color;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import org.freixas.jcalendar.JCalendarCombo;

/**
 *
 * @author v6222
 */
public class Caso extends javax.swing.JDialog {

    int n;
    Date fechaHoy;
    Casos caso;
    /**
     * Creates new form Caso
     */
    public Caso(int n, String dato) {
        initComponents();
        this.n = n;
        setTitle( dato + this.getTitle());
        adaptaciones();
    }

    public void adaptaciones(){
        setModal(true);
        this.setLocationRelativeTo(null);
        caso = null;
        fechaHoy = cFechaI.getDate();
        cFechaF.setSelectedIndex(-1);
        setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tNumero = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        bAceptar = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();
        tEstado = new javax.swing.JTextField();
        tDNI = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cFechaI = new org.freixas.jcalendar.JCalendarCombo();
        cFechaF = new org.freixas.jcalendar.JCalendarCombo();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(" Caso");
        setName("Caso"); // NOI18N

        jLabel3.setText("Fecha Fin:");

        jLabel4.setText("Estado:");

        jLabel5.setText("DNI Cliente:");

        jLabel1.setText("Número:");

        bAceptar.setText("Consultar");
        bAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAceptarActionPerformed(evt);
            }
        });

        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        tEstado.setEnabled(false);

        tDNI.setEnabled(false);

        jLabel2.setText("Fecha Inicio:");

        cFechaI.setEditable(true);
        cFechaI.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "martes 20 de marzo de 2018" }));
        cFechaI.setEnabled(false);

        cFechaF.setEditable(true);
        cFechaF.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 206, Short.MAX_VALUE)
                        .addComponent(bCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tEstado)
                            .addComponent(tNumero)
                            .addComponent(cFechaI, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                            .addComponent(cFechaF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tDNI))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cFechaI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cFechaF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAceptar)
                    .addComponent(bCancelar))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAceptarActionPerformed
        // TODO add your handling code here:
        try{
            validar(1, tNumero, "^[0-9]{1,5}$");
                        
            if(bAceptar.getText().equals("Consultar")){
                caso = Main.consultarCaso(tNumero.getText());
                
                if(caso == null){
                    habilitarCliente();
                    bAceptar.setText("Añadir");
                }
                else{
                    if(n == 2){
                        llenarDatos(caso);
                        bAceptar.setText("Eliminar");
                    }
                    else{
                        habilitarCliente();
                        cFechaF.setEnabled(true);
                        llenarDatos(caso);
                        bAceptar.setText("Modificar");
                    }
                    
                }
            }
            else{
                validar(5, tEstado, "^[A-Z]{1}$");
                validar(1, tDNI, "^[0-9]{8}[A-Z]$");
                validarFecha(9, fechaHoy, cFechaI);
                if(cFechaF == null){
                    validarFecha(9, cFechaI.getDate(), cFechaF);
                }
                if(bAceptar.getText().equals("Añadir")){
                    cargarCliente(tDNI.getText());
                    Main.crearCaso(tNumero.getText(), cFechaI.getDate(), cFechaF.getDate(), tEstado.getText());
                    JOptionPane.showMessageDialog(this, "Caso añadido correctamente.");
                    Main.cerrar(this);
                }
                else if(bAceptar.getText().equals("Eliminar")){
                    Main.eliminarCaso(tNumero.getText());
                    JOptionPane.showMessageDialog(this, "Caso eliminado correctamente.");
                    Main.cerrar(this);
                }
                else{
                    cargarCliente(tDNI.getText());
                    caso.setNumExp(tNumero.getText());
                    caso.setFechaI(cFechaI.getDate());
                    caso.setFechaF(cFechaF.getDate());
                    caso.setEstado(tEstado.getText());
                    Main.setCaso(caso);
                    Main.modificarCaso();
                    JOptionPane.showMessageDialog(this, "Caso modificado correctamente.");
                    Main.cerrar(this);
                }
                
            }
            
        }
        catch(Errores.Error e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        catch(Exception ee){
            JOptionPane.showMessageDialog(this, ee.getClass());
        }
    }//GEN-LAST:event_bAceptarActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        // TODO add your handling code here:
        Main.cerrar(this);
    }//GEN-LAST:event_bCancelarActionPerformed

    private void validar(int error, JTextField dato, String patron) throws Exception{
        Pattern p = Pattern.compile(patron);
        Matcher m = p.matcher(dato.getText());
        if(m.matches()){
            dato.setBackground(Color.white);
        }
        else{
            dato.setBackground(Color.red);
            dato.grabFocus();
            throw new Error(error);
        }
    }
    
    private void validarFecha(int error, Date fechaI, JCalendarCombo fechaF) throws Exception{
        if(fechaI.before(fechaF.getDate())){
            fechaF.setBackground(Color.red);
            fechaF.grabFocus();
            throw new Error(error);
        }
        else{
            fechaF.setBackground(Color.white);
        }
    }
    
    private void habilitarCliente(){
        tNumero.setEnabled(false);
        cFechaI.setEnabled(true);
        cFechaF.setEnabled(true);
        tEstado.setEnabled(true);
        tDNI.setEnabled(true);
    }
    
    private void llenarDatos(Casos caso){
        tNumero.setText(caso.getNumExp());
        tEstado.setText(caso.getEstado());
        tDNI.setText(caso.getClientedni().getDni());
        cFechaI.setDate(caso.getFechaI());
        cFechaF.setDate(caso.getFechaF());
        
    }
    
    private void cargarCliente(String dni) throws Exception{
        Clientes clie = null;
        clie = Main.consultarCliente(dni);
        if(clie == null){
            tDNI.setBackground(Color.red);
            tDNI.grabFocus();
            throw new Error(6);
        }
    }   
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAceptar;
    private javax.swing.JButton bCancelar;
    private org.freixas.jcalendar.JCalendarCombo cFechaF;
    private org.freixas.jcalendar.JCalendarCombo cFechaI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField tDNI;
    private javax.swing.JTextField tEstado;
    private javax.swing.JTextField tNumero;
    // End of variables declaration//GEN-END:variables
}
