/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controladora.Main;
import java.awt.*;
import java.util.regex.*;
import Errores.Error;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import org.freixas.jcalendar.JCalendarCombo;

/**
 *
 * @author Jon
 */
public class Principal extends javax.swing.JFrame {
    
    String contador ="123456";
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        getContentPane().setBackground(this.getBackground());
        adaptaciones();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void adaptaciones(){
        
        ImageIcon imagen=new ImageIcon("src/Img/logo.png");
	Icon icono= new ImageIcon(imagen.getImage().getScaledInstance(lLogo.getWidth(), lLogo.getHeight(),Image.SCALE_DEFAULT));
	lLogo.setIcon(icono);
	lLogo.repaint();
        imagen=new ImageIcon("src/Img/fondo.png");
	icono=new ImageIcon(imagen.getImage().getScaledInstance(lFondo.getWidth(), lFondo.getHeight(),Image.SCALE_DEFAULT));
	lFondo.setIcon(icono);
	lFondo.repaint();
        bAñadir.setVisible(false);
        jPanel2.setVisible(false);
        jpHijo2.setVisible(false);
        jpHijo3.setVisible(false);
        jpHijo4.setVisible(false);
        jpHijo5.setVisible(false);
        jpHijo6.setVisible(false);
        tfNombre.grabFocus();
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgCategoria = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        lLogo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rbFamiliar = new javax.swing.JRadioButton();
        rdIndividual = new javax.swing.JRadioButton();
        lFondo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfCorreo = new javax.swing.JTextField();
        tfTelefono = new javax.swing.JTextField();
        tfApellidos = new javax.swing.JTextField();
        tfNombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        bIncribir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jpHijo1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        tfNombreHijo1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jCalendarCombo1 = new org.freixas.jcalendar.JCalendarCombo();
        jpHijo2 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        tfNombreHijo2 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jCalendarCombo2 = new org.freixas.jcalendar.JCalendarCombo();
        jpHijo3 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        tfNombreHijo3 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jCalendarCombo3 = new org.freixas.jcalendar.JCalendarCombo();
        jpHijo4 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        tfNombreHijo4 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jCalendarCombo4 = new org.freixas.jcalendar.JCalendarCombo();
        jpHijo5 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        tfNombreHijo5 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jCalendarCombo5 = new org.freixas.jcalendar.JCalendarCombo();
        jpHijo6 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        tfNombreHijo6 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jCalendarCombo6 = new org.freixas.jcalendar.JCalendarCombo();
        bAñadir = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        bSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 51));

        jLabel1.setFont(new java.awt.Font("Californian FB", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hoja de Inscripción");

        lLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lLogo.setRequestFocusEnabled(false);
        lLogo.setVerifyInputWhenFocusTarget(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 51));
        jLabel2.setText("Sí, deseo/deseamos hacerme/hacernos socio/s del Zoo-Club. Couta de ingreso 15 €.");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Categoría:");

        bgCategoria.add(rbFamiliar);
        rbFamiliar.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        rbFamiliar.setText("Familiar: 68€");
        rbFamiliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFamiliarActionPerformed(evt);
            }
        });

        bgCategoria.add(rdIndividual);
        rdIndividual.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        rdIndividual.setSelected(true);
        rdIndividual.setText("Individual: 32€");
        rdIndividual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdIndividualActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setText("Nombre:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setText("Apellidos:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setText("Correo Electrónico:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel7.setText("Teléfono:");

        tfNombre.setToolTipText("");
        tfNombre.setName(""); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Hijos: (Sólo menores de edad y en categoría Familiar)");

        bIncribir.setBackground(new java.awt.Color(102, 255, 102));
        bIncribir.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        bIncribir.setForeground(new java.awt.Color(102, 153, 255));
        bIncribir.setText("Inscribirse");
        bIncribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIncribirActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));

        jpHijo1.setBackground(new java.awt.Color(204, 204, 204));
        jpHijo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));

        jLabel9.setText("Nombre:");

        jLabel11.setText("Fecha de Nac.:");

        jButton1.setBackground(new java.awt.Color(102, 255, 102));
        jButton1.setFont(new java.awt.Font("Engravers MT", 0, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 51));
        jButton1.setText("X");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpHijo1Layout = new javax.swing.GroupLayout(jpHijo1);
        jpHijo1.setLayout(jpHijo1Layout);
        jpHijo1Layout.setHorizontalGroup(
            jpHijo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHijo1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfNombreHijo1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCalendarCombo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1))
        );
        jpHijo1Layout.setVerticalGroup(
            jpHijo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHijo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(tfNombreHijo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel9)
                .addComponent(jLabel11)
                .addComponent(jButton1)
                .addComponent(jCalendarCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpHijo2.setBackground(new java.awt.Color(204, 204, 204));
        jpHijo2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));

        jLabel22.setText("Nombre:");

        jLabel23.setText("Fecha de Nac.:");

        jButton2.setBackground(new java.awt.Color(102, 255, 102));
        jButton2.setFont(new java.awt.Font("Engravers MT", 0, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 51));
        jButton2.setText("X");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpHijo2Layout = new javax.swing.GroupLayout(jpHijo2);
        jpHijo2.setLayout(jpHijo2Layout);
        jpHijo2Layout.setHorizontalGroup(
            jpHijo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHijo2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfNombreHijo2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCalendarCombo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2))
        );
        jpHijo2Layout.setVerticalGroup(
            jpHijo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHijo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(tfNombreHijo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel22)
                .addComponent(jLabel23)
                .addComponent(jButton2)
                .addComponent(jCalendarCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpHijo3.setBackground(new java.awt.Color(204, 204, 204));
        jpHijo3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));

        jLabel24.setText("Nombre:");

        jLabel25.setText("Fecha de Nac.:");

        jButton3.setBackground(new java.awt.Color(102, 255, 102));
        jButton3.setFont(new java.awt.Font("Engravers MT", 0, 16)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 0, 51));
        jButton3.setText("X");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpHijo3Layout = new javax.swing.GroupLayout(jpHijo3);
        jpHijo3.setLayout(jpHijo3Layout);
        jpHijo3Layout.setHorizontalGroup(
            jpHijo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHijo3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfNombreHijo3, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCalendarCombo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3))
        );
        jpHijo3Layout.setVerticalGroup(
            jpHijo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHijo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(tfNombreHijo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel24)
                .addComponent(jLabel25)
                .addComponent(jButton3)
                .addComponent(jCalendarCombo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpHijo4.setBackground(new java.awt.Color(204, 204, 204));
        jpHijo4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));

        jLabel26.setText("Nombre:");

        jLabel27.setText("Fecha de Nac.:");

        jButton4.setBackground(new java.awt.Color(102, 255, 102));
        jButton4.setFont(new java.awt.Font("Engravers MT", 0, 16)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 0, 51));
        jButton4.setText("X");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpHijo4Layout = new javax.swing.GroupLayout(jpHijo4);
        jpHijo4.setLayout(jpHijo4Layout);
        jpHijo4Layout.setHorizontalGroup(
            jpHijo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHijo4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfNombreHijo4, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCalendarCombo4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4))
        );
        jpHijo4Layout.setVerticalGroup(
            jpHijo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel26)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpHijo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jCalendarCombo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton4)
                .addComponent(jLabel27)
                .addComponent(tfNombreHijo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpHijo5.setBackground(new java.awt.Color(204, 204, 204));
        jpHijo5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));

        jLabel28.setText("Nombre:");

        jLabel29.setText("Fecha de Nac.:");

        jButton5.setBackground(new java.awt.Color(102, 255, 102));
        jButton5.setFont(new java.awt.Font("Engravers MT", 0, 16)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 0, 51));
        jButton5.setText("X");
        jButton5.setEnabled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpHijo5Layout = new javax.swing.GroupLayout(jpHijo5);
        jpHijo5.setLayout(jpHijo5Layout);
        jpHijo5Layout.setHorizontalGroup(
            jpHijo5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHijo5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfNombreHijo5, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCalendarCombo5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5))
        );
        jpHijo5Layout.setVerticalGroup(
            jpHijo5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHijo5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(tfNombreHijo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel28)
                .addComponent(jLabel29)
                .addComponent(jButton5)
                .addComponent(jCalendarCombo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpHijo6.setBackground(new java.awt.Color(204, 204, 204));
        jpHijo6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));

        jLabel30.setText("Nombre:");

        jLabel31.setText("Fecha de Nac.:");

        jButton6.setBackground(new java.awt.Color(102, 255, 102));
        jButton6.setFont(new java.awt.Font("Engravers MT", 0, 16)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 0, 51));
        jButton6.setText("X");
        jButton6.setEnabled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpHijo6Layout = new javax.swing.GroupLayout(jpHijo6);
        jpHijo6.setLayout(jpHijo6Layout);
        jpHijo6Layout.setHorizontalGroup(
            jpHijo6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHijo6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfNombreHijo6, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCalendarCombo6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6))
        );
        jpHijo6Layout.setVerticalGroup(
            jpHijo6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHijo6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(tfNombreHijo6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel30)
                .addComponent(jLabel31)
                .addComponent(jButton6)
                .addComponent(jCalendarCombo6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpHijo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpHijo2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpHijo3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpHijo5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpHijo4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpHijo6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpHijo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpHijo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpHijo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpHijo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpHijo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jpHijo6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bAñadir.setBackground(new java.awt.Color(211, 216, 183));
        bAñadir.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        bAñadir.setForeground(new java.awt.Color(0, 153, 51));
        bAñadir.setText("Añadir Hijo");
        bAñadir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAñadirActionPerformed(evt);
            }
        });

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 204, 51));
        jLabel12.setText("<html><u>Zoo de Barcelona</u></html>");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, 270, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 153, 51));
        jLabel10.setText("<html>Atención!: Esta es una hoja de inscripción de ejemplo, si desea realmente Inscribirse<br>al Zoo-Club de Barcelona, pinche en el siguiente enlace</html>\n        ");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 880, 75));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 33, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(309, 309, 309)
                                .addComponent(rdIndividual))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(110, 110, 110)
                                .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(100, 100, 100)
                                .addComponent(tfApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(tfCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(102, 102, 102)
                                .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(152, 152, 152)
                        .addComponent(lFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(145, 145, 145))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(26, 26, 26)
                                .addComponent(rbFamiliar))
                            .addComponent(bAñadir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(424, 424, 424)
                        .addComponent(bIncribir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rbFamiliar)
                                .addComponent(rdIndividual)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(tfApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tfCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bAñadir)
                .addGap(1, 1, 1)
                .addComponent(bIncribir)
                .addGap(1, 1, 1)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        bSalir.setBackground(new java.awt.Color(102, 255, 102));
        bSalir.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        bSalir.setForeground(new java.awt.Color(102, 153, 255));
        bSalir.setText("Salir");
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostrar(){
        
        contador = contador.substring(1, contador.length());
        
        if(contador.length()==0){
            contador = "7";
        }
        else if(contador.substring(0,1).equals("7") && contador.length() > 1){
            contador = contador.substring(1, contador.length());
        }
        
        int numero = Integer.parseInt(contador.substring(0,1));
        
        switch(numero){
            case 1:
                jpHijo1.setVisible(true);
                break;
            case 2:
                jpHijo2.setVisible(true);
                break;
            case 3:
                jpHijo3.setVisible(true);
                break;
            case 4:
                jpHijo4.setVisible(true);
                break;
            case 5:
                jpHijo5.setVisible(true);
                break;
            case 6:
                jpHijo6.setVisible(true);
                break;
            default: 
                JOptionPane.showMessageDialog(this, "No se puede añadir más Hij@s, el límite de agregado es de 6 hij@s.");
                bAñadir.setVisible(false);
                break;
        }
    }
    
    private void aceptado(JTextField nombre, JCalendarCombo calendario){
        nombre.setEnabled(false);
        calendario.setEnabled(false);
        JOptionPane.showMessageDialog(this, "Hij@ Añadido correctamente.");
    }
    
    private void eliminar(JTextField nombre, JCalendarCombo calendario, JPanel panel, JButton boton){
        nombre.setEnabled(true);
        calendario.setEnabled(true);
        nombre.setText("");
        calendario.setDate(new java.util.Date());
        boton.setEnabled(false);
        panel.setVisible(false);
        JOptionPane.showMessageDialog(this, "Hij@ se ha Eliminado correctamente.");
    }
    
    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        // TODO add your handling code here:
        Main.ver(this);
    }//GEN-LAST:event_bSalirActionPerformed

    private void bAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAñadirActionPerformed
        // TODO add your handling code here:
        int numero = Integer.parseInt(contador.substring(0,1));
        try{
            switch(numero){
                case 1:
                    validarHijo(tfNombreHijo1, jCalendarCombo1, jButton1);
                    break;

                case 2:
                    validarHijo(tfNombreHijo2, jCalendarCombo2, jButton2);
                    break;
                
                case 3:
                    validarHijo(tfNombreHijo3, jCalendarCombo3, jButton3);
                    break;
                
                case 4:
                    validarHijo(tfNombreHijo4, jCalendarCombo4, jButton4);
                    break;
                
                case 5:
                    validarHijo(tfNombreHijo5, jCalendarCombo5, jButton5);
                    break;
                
                case 6:
                    validarHijo(tfNombreHijo6, jCalendarCombo6, jButton6);
                    break;
                    
                case 7:
                    mostrar();
                    break;
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getClass());
        }
    }//GEN-LAST:event_bAñadirActionPerformed
    
    private void validarHijo(JTextField nombre, JCalendarCombo fecha, JButton boton) throws Exception{
        try{
            validar(nombre, "^[A-Z][a-z]{2,}([ ][A-Z][a-z]{1,})*$",1);
            validarFecha(fecha);
            aceptado(nombre, fecha);
            boton.setEnabled(true);
            mostrar();
        }
        catch(Error e){
            JOptionPane.showMessageDialog(this, "El Campo en Rojo es Obligatorio y tiene un formato: " + e.getMessage());
        }
    }
    
    private void agregarHijo(){
        java.text.SimpleDateFormat ValFecha = new java.text.SimpleDateFormat("yyyy-MM-dd");
        for(int x =1; x<(7) ;x++){
            if(!contador.contains(String.valueOf(x))){
                switch(x){
                    case 1:
                        Main.agregarH(tfNombreHijo1.getText(), ValFecha.format(jCalendarCombo1.getDate()));
                        break;
                    case 2:
                        Main.agregarH(tfNombreHijo2.getText(), ValFecha.format(jCalendarCombo2.getDate()));
                        break;
                    case 3:
                        Main.agregarH(tfNombreHijo3.getText(), ValFecha.format(jCalendarCombo3.getDate()));
                        break;
                    case 4:
                        Main.agregarH(tfNombreHijo4.getText(), ValFecha.format(jCalendarCombo4.getDate()));
                        break;
                    case 5:
                        Main.agregarH(tfNombreHijo5.getText(), ValFecha.format(jCalendarCombo5.getDate()));
                        break;
                    case 6:
                        Main.agregarH(tfNombreHijo6.getText(), ValFecha.format(jCalendarCombo6.getDate()));
                        break;
                }
            }
        }
    }
    
    private void bIncribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIncribirActionPerformed
        // TODO add your handling code here:
        try{
            validar(tfNombre, "^[A-Z][a-z]{2,}([ ][A-Z][a-z]{1,})*$",1);
            validar(tfApellidos, "^[A-Z][a-z]{1,}([ ][A-Z][a-z]{1,})*$",2);
            validar(tfTelefono, "^[6-9][0-9]{8}$",3);
            validar(tfCorreo, "^[a-z0-9]{1,}[@][a-z0-9]{1,}[.][a-z]{2,}$",4);
            
            Main.agregar(tfNombre.getText(), tfApellidos.getText(), tfTelefono.getText(), tfCorreo.getText());

            if(rbFamiliar.isSelected()){
                agregarHijo();
            }
            
            Main.completado(this);
        }
        catch(Error e){
            JOptionPane.showMessageDialog(this, "El Campo en Rojo es Obligatorio y tiene un formato: " + e.getMessage());
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getClass());
        }
    }//GEN-LAST:event_bIncribirActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        eliminar(tfNombreHijo6, jCalendarCombo6, jpHijo6, jButton6);
        contador += "6";
        bAñadir.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        eliminar(tfNombreHijo5, jCalendarCombo5, jpHijo5, jButton5);
        contador += "5";
        bAñadir.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        eliminar(tfNombreHijo4, jCalendarCombo4, jpHijo4, jButton4);
        contador += "4";
        bAñadir.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        eliminar(tfNombreHijo3, jCalendarCombo3, jpHijo3, jButton3);
        contador += "3";
        bAñadir.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        eliminar(tfNombreHijo2, jCalendarCombo2, jpHijo2, jButton2);
        contador += "2";
        bAñadir.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        eliminar(tfNombreHijo1, jCalendarCombo1, jpHijo1, jButton1);
        contador += "1";
        bAñadir.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rdIndividualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdIndividualActionPerformed
        // TODO add your handling code here:
        jPanel2.setVisible(false);
        bAñadir.setVisible(false);
    }//GEN-LAST:event_rdIndividualActionPerformed

    private void rbFamiliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFamiliarActionPerformed
        // TODO add your handling code here:
        jPanel2.setVisible(true);
        bAñadir.setVisible(true);
    }//GEN-LAST:event_rbFamiliarActionPerformed

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        Desktop desktop = Desktop.getDesktop();
        URI uri;
        try {
            uri = new URI("https://www.zoobarcelona.cat/");
            desktop.browse(uri);
        } catch (URISyntaxException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel12MouseClicked
    
    private void validar(javax.swing.JTextField campo, String condicion, int error) throws Exception{
        Pattern patron = Pattern.compile(condicion);
        Matcher mat = patron.matcher(campo.getText());
        if(!mat.matches()){
            campo.grabFocus();
            campo.setBackground(Color.red);
            throw new Error(error);
        }
        else{
            campo.setBackground(Color.white);
        }
    }
    
    private void validarFecha(JCalendarCombo calendario) throws Exception{
        java.util.Date fecha = new java.util.Date();
        java.text.SimpleDateFormat ValFecha = new java.text.SimpleDateFormat("yyyyMMdd");
        int fe = Integer.valueOf(ValFecha.format(calendario.getDate()));
        int fs = Integer.valueOf(ValFecha.format(fecha));
        if(fe>fs){
            calendario.grabFocus();
            calendario.setBackground(Color.red);
            throw new Error(5);
        }
        else{
            calendario.setBackground(Color.white);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAñadir;
    private javax.swing.JButton bIncribir;
    private javax.swing.JButton bSalir;
    private javax.swing.ButtonGroup bgCategoria;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private org.freixas.jcalendar.JCalendarCombo jCalendarCombo1;
    private org.freixas.jcalendar.JCalendarCombo jCalendarCombo2;
    private org.freixas.jcalendar.JCalendarCombo jCalendarCombo3;
    private org.freixas.jcalendar.JCalendarCombo jCalendarCombo4;
    private org.freixas.jcalendar.JCalendarCombo jCalendarCombo5;
    private org.freixas.jcalendar.JCalendarCombo jCalendarCombo6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jpHijo1;
    private javax.swing.JPanel jpHijo2;
    private javax.swing.JPanel jpHijo3;
    private javax.swing.JPanel jpHijo4;
    private javax.swing.JPanel jpHijo5;
    private javax.swing.JPanel jpHijo6;
    private javax.swing.JLabel lFondo;
    private javax.swing.JLabel lLogo;
    private javax.swing.JRadioButton rbFamiliar;
    private javax.swing.JRadioButton rdIndividual;
    private javax.swing.JTextField tfApellidos;
    private javax.swing.JTextField tfCorreo;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfNombreHijo1;
    private javax.swing.JTextField tfNombreHijo2;
    private javax.swing.JTextField tfNombreHijo3;
    private javax.swing.JTextField tfNombreHijo4;
    private javax.swing.JTextField tfNombreHijo5;
    private javax.swing.JTextField tfNombreHijo6;
    private javax.swing.JTextField tfTelefono;
    // End of variables declaration//GEN-END:variables
}
